#!/usr/bin/env python3
"""Regenerate the debug picker from authored map landings and area bounds.

Inputs are development references, not runtime dependencies. See
cpp/docs/debug-tools.md for their provenance and the reproduction command.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import re


def catalogue(source: Path, regions: Path) -> list[dict]:
    def read(name: str) -> str:
        return (source / "src/data" / name).read_text()

    psi = re.findall(r"\.WORD \$([0-9A-F]+) ;X\s+\.WORD \$([0-9A-F]+) ;Y",
                     read("psi_teleport_destinations.asm"))
    towns = ["", "Onett", "Twoson", "Threed", "Saturn Valley", "Fourside",
             "Winters", "Summers", "Scaraba", "Dalaam", "Deep Darkness",
             "Tenda Village", "Lost Underworld", "", "Dusty Dunes Desert"]
    entries = [dict(name=name, id=i, x=int(psi[i][0], 16)*8, y=int(psi[i][1], 16)*8)
               for i, name in enumerate(towns) if name]
    warps = [(i, int(x, 16)*8, int(y, 16)*8) for i, (x, y) in enumerate(
        re.findall(r"\.WORD \$([0-9A-F]+), \$([0-9A-F]+)", read("map/teleport_destinations.asm"))) if i]
    doors = []
    for door_id, body in re.findall(r"DOOR_ENTRY_(\d+):\s*(.*?)(?=DOOR_ENTRY_|\Z)",
                                    read("map/door_data.asm"), re.S):
        landing = re.search(r"\.WORD \$([0-9A-F]+), \$([0-9A-F]+)\s+\.BYTE", body)
        if landing:
            y, x = (int(n, 16) for n in landing.groups())
            # DOOR_TRANSITION adds a tile except when UNKNOWN_C3E1D8 maps the
            # encoded direction to RIGHT (2). The upper two Y bits are direction.
            doors.append((int(door_id), x*8 + (0 if y >> 14 == 2 else 8), (y & 0x3fff)*8))
    with regions.open(newline="") as handle:
        areas = sorted(csv.DictReader(handle), key=lambda area: area["filename"])
    for area in areas:
        for key in ("x0", "x1", "y0", "y1"):
            area[key] = int(area[key])

    def contains(area: dict, x: int, y: int) -> bool:
        return area["x0"] <= x < area["x1"] and area["y0"] <= y < area["y1"]

    def label(area: dict) -> str:
        return area["filename"].replace("_", " / ").replace("-", " ")

    for i, area in enumerate(areas):
        candidates = [p for p in warps if contains(area, *p[1:])] or [
            p for p in doors if contains(area, *p[1:])]
        if not candidates:
            raise ValueError(f"No authored landing in {area['filename']}")
        _, x, y = min(candidates, key=lambda p: (2*p[1]-area["x0"]-area["x1"])**2 +
                      (2*p[2]-area["y0"]-area["y1"])**2)
        entries.append(dict(name="Area: " + label(area), id=1000+i, x=x, y=y))

    def location(x: int, y: int) -> str:
        candidates = [area for area in areas if contains(area, x, y)]
        return label(min(candidates, key=lambda a: (a["x1"]-a["x0"])*(a["y1"]-a["y0"]))) if candidates else "Map"

    for points, prefix, base in ((warps, "Warp", 2000), (doors, "Entrance", 3000)):
        entries.extend(dict(name=f"{prefix} {i:03}: {location(x, y)}", id=base+i, x=x, y=y)
                       for i, x, y in points)
    if (len(areas), len(warps), len(doors)) != (385, 233, 841):
        raise ValueError("Reference table counts changed; review destination coverage before regenerating")
    if len({entry["id"] for entry in entries}) != len(entries):
        raise ValueError("Duplicate destination ID")
    for entry in entries:
        if not (0 <= entry["x"] < 8192 and 0 <= entry["y"] < 10240 and
                entry["x"] % 8 == 0 and entry["y"] % 8 == 0):
            raise ValueError(f"Invalid map landing: {entry}")
    return entries


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--regions", type=Path, required=True)
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parents[1] / "include/eb/debug_destinations.inc")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    entries = catalogue(args.source_root, args.regions)
    rendered = ("// Generated by cpp/tools/generate_debug_destinations.py.\n"
                "// Authored landings and area labels: see cpp/docs/debug-tools.md.\n" +
                "".join(f'    {{{json.dumps(p["name"], ensure_ascii=True)},{p["id"]},{p["x"]},{p["y"]}}},\n'
                        for p in entries))
    if args.check:
        if args.output.read_text() != rendered:
            raise SystemExit("Destination catalogue is stale")
    else:
        args.output.write_text(rendered)
    print(f"PASS {len(entries)} destinations: 13 towns, 385 areas, 233 warps, 841 entrances")


if __name__ == "__main__":
    main()
