#pragma once

#include "eb/direct_scene.hpp"
#include "eb/native/battle_background.hpp"
#include <optional>
#include <stdexcept>

namespace eb::native {
struct BattleBackgroundPair {
  unsigned primary{}, secondary{}, style{};
  bool operator==(const BattleBackgroundPair &) const = default;
};
struct BattleBackgroundArtworkDependency {
  unsigned layer{}, first_unpublished_tile{};
  bool operator==(const BattleBackgroundArtworkDependency &) const = default;
};
class BattleBackgroundArtworkRequired : public std::runtime_error {
public:
  explicit BattleBackgroundArtworkRequired(BattleBackgroundArtworkDependency d)
      : std::runtime_error(
            "Battle background requires external artwork publication"),
        dependency(d) {}
  const BattleBackgroundArtworkDependency dependency;
};
enum class BattleBackgroundBlend { Opaque, HalfAdd };
enum class BattleArtworkPublication { Ordinary, GiygasPrayer };
enum class BattlePaletteDependency {
  // The shared-artwork source path publishes a zeroed palette through its
  // unset destination, clearing frame/queue/draw/display state. This is not
  // a write to palette slot0 and requires the corresponding scene owners.
  ResetSceneAndFrameState
};
class BattlePaletteRestorationRequired : public std::runtime_error {
public:
  explicit BattlePaletteRestorationRequired(BattlePaletteDependency value)
      : std::runtime_error("Battle palette restoration requires native scene/frame reset"),
        dependency(value) {}
  const BattlePaletteDependency dependency;
};
// Explicit incoming display state for LOAD_BATTLE_BG. Four-bit artwork is
// generated during loading using the preceding parity/alternate gate. Two-bit
// artwork is first generated by the next logical tick and retains its incoming
// scroll until then. A fresh controller can use these zero-initialized values.
struct BattleBackgroundStart {
  unsigned frame_parity{};
  bool previous_alternate{}, defeated{};
  BattleBackgroundTick::Scroll primary_scroll{}, secondary_scroll{}, effects{};
  BattleBackgroundBlend inherited_blend = BattleBackgroundBlend::Opaque;
  std::uint16_t reflect_duration{}, green_background_duration{};
  PaletteColor backdrop{};
  // A loader with no second layer disables it without clearing its retained
  // palette. Transfer this value from the preceding scene when replacing it;
  // the zero default represents a fresh, explicitly cold scene owner.
  BattleBackgroundPalette retained_secondary_palette;
};
struct BattleBackgroundEffects {
  bool darkening{}, opening_letterbox{};
  std::uint16_t brightness = 0xffff;
  std::uint16_t reflect_duration{}, green_background_duration{};
  std::uint16_t vertical_duration{}, vertical_hold{}, wobble_duration{},
      shake_duration{}, minimum_wait{}, red_duration{}, green_duration{};
  std::uint16_t horizontal_offset{}, vertical_offset{};
  unsigned top_end{}, bottom_start = 224;
  std::uint16_t opening_top = 0x7000, opening_bottom = 0x7000;
  PaletteColor backdrop{}, addition{};
  bool additive_flash{};
  bool operator==(const BattleBackgroundEffects &) const = default;
};
struct BattleBackgroundSceneTick {
  unsigned frame_parity{};
  bool defeated{};
};
struct BattleBackgroundSceneFrame {
  BattleBackgroundPair pair;
  BattleBackgroundFrame primary;
  std::optional<BattleBackgroundFrame> secondary;
  bool shared_artwork{}, secondary_main{};
  BattleBackgroundBlend blend{};
  BattleBackgroundEffects effects;
  // Native background-only scene. Enemy artwork, PSI, UI and the independent
  // swirl controller are composed by their owners. Sampling never advances
  // time.
  PaletteColor sample(int x, unsigned y) const;
  std::shared_ptr<const DirectSceneFrame>
  draw(unsigned width = 256, std::uint64_t frame = 0,
       std::uint64_t identity = 0) const;
};
class BattleBackgroundScenes;
class BattleBackgroundScene {
public:
  BattleBackgroundSceneFrame snapshot() const;
  const BattleBackgroundEffects &effects() const { return effects_; }
  const BattleBackground &primary() const { return primary_; }
  const std::optional<BattleBackground> &secondary() const {
    return secondary_;
  }
  bool alternate_distortion() const { return alternate_; }
  void advance(BattleBackgroundSceneTick);
  void darken() { effects_.darkening = true; }
  void open_letterbox() { effects_.opening_letterbox = true; }
  void reflect(std::uint16_t duration) { effects_.reflect_duration = duration; }
  void green_background(std::uint16_t duration) {
    effects_.green_background_duration = duration;
  }
  void shake(std::uint16_t duration) { effects_.shake_duration = duration; }
  void wobble(std::uint16_t duration) { effects_.wobble_duration = duration; }
  void quake(unsigned duration, std::uint16_t hold = 0);
  void wait(std::uint16_t duration) { effects_.minimum_wait = duration; }
  void flash_red(std::uint16_t duration) { effects_.red_duration = duration; }
  void flash_green(std::uint16_t duration) {
    effects_.green_duration = duration;
  }
  void apply_palette_brightness(std::uint16_t factor);
  BattleBackgroundPalette retained_secondary_palette() const;
  std::optional<BattlePaletteDependency> palette_restoration_dependency() const;
  // Complete ordinary C2DE96: restore both palette bases and the active
  // publication slots, including index0, without ticking any controller.
  // A shared-artwork reset dependency rejects before these mutations.
  void restore_palette(ScenePalette &);

private:
  friend class BattleBackgroundScenes;
  struct Content;
  BattleBackgroundScene(std::shared_ptr<const Content>, BattleBackgroundPair,
                        BattleBackgroundStart);
  std::shared_ptr<const Content> content_;
  BattleBackgroundPair pair_;
  BattleBackground primary_;
  std::optional<BattleBackground> secondary_;
  BattleBackgroundPalette inactive_secondary_palette_;
  BattleBackgroundBlend blend_{};
  BattleBackgroundEffects effects_;
  bool shared_artwork_{}, alternate_{};
};
class BattleBackgroundScenes {
public:
  BattleBackgroundScenes(std::span<const std::uint8_t>, GameVersion);
  unsigned size() const;
  BattleBackgroundPair selection(unsigned battle) const;
  // Referenced artwork beyond the authored load is supplied by a
  // separate controller. Preparation rejects it until that owner is ported.
  std::optional<BattleBackgroundArtworkDependency> artwork_dependency(
      BattleBackgroundPair,
      BattleArtworkPublication = BattleArtworkPublication::Ordinary) const;
  // The battle selector supplies the extended prayer publication for group478.
  // Explicit pair callers must pass that context themselves.
  BattleBackgroundScene prepare(unsigned battle,
                                BattleBackgroundStart = {}) const;
  BattleBackgroundScene prepare(
      BattleBackgroundPair, BattleBackgroundStart = {},
      BattleArtworkPublication = BattleArtworkPublication::Ordinary) const;

private:
  std::shared_ptr<const BattleBackgroundScene::Content> content_;
};
} // namespace eb::native
