#pragma once

#include "eb/direct_scene.hpp"
#include "eb/native/battle_background.hpp"
#include <optional>
#include <stdexcept>

namespace eb::native {
namespace battle {
struct PaletteBankState;
class PsiDisplayState;
struct BackgroundDisplayState;
class BackgroundLoader;
}
struct BattleBackgroundPair {
  unsigned primary{}, secondary{}, style{};
  bool operator==(const BattleBackgroundPair &) const = default;
};
struct BattleBackgroundArtworkDependency {
  unsigned layer{}, first_unpublished_tile{};
  bool operator==(const BattleBackgroundArtworkDependency &) const = default;
};
class BattleBackgroundArtworkRequired : public std::runtime_error {
public:
  explicit BattleBackgroundArtworkRequired(BattleBackgroundArtworkDependency d)
      : std::runtime_error(
            "Battle background requires external artwork publication"),
        dependency(d) {}
  const BattleBackgroundArtworkDependency dependency;
};
enum class BattleBackgroundBlend { Opaque, HalfAdd };
enum class BattleArtworkPublication { Ordinary, GiygasPrayer };
enum class BattlePaletteDependency {
  // The shared-artwork source path publishes a zeroed palette through its
  // unset destination, clearing frame/queue/draw/display state. This is not
  // a write to palette slot0 and requires the corresponding scene owners.
  ResetSceneAndFrameState,
  // C2E08E still writes the disabled secondary's retained destination. A cold
  // destination aliases low WRAM; a prior scene may retain a palette bank.
  // Palette colors alone cannot identify that destination or its shift policy.
  InactiveSecondaryDestination
};
// The source unset palette pointer writes32 zero bytes to the scene's low
// mirrors. Palette storage cannot complete this operation by itself.
class BattleSceneFrameReset {
public:
  virtual ~BattleSceneFrameReset() = default;
  virtual void validate_scene_and_frame_reset() const = 0;
  virtual void reset_scene_and_frame_state() = 0;
};
class BattlePaletteRestorationRequired : public std::runtime_error {
public:
  explicit BattlePaletteRestorationRequired(BattlePaletteDependency value)
      : std::runtime_error(
            value == BattlePaletteDependency::ResetSceneAndFrameState
                ? "Battle palette restoration requires native scene/frame reset"
                : "Battle brightness requires the inactive secondary destination"),
        dependency(value) {}
  const BattlePaletteDependency dependency;
};
struct BattleBackgroundLayerMetadata {
  std::uint8_t target_layer{}, freeze_palette_scrolling{};
  // Global palette color identity; absence is the source low-WRAM destination.
  std::optional<unsigned> palette_base;
  bool operator==(const BattleBackgroundLayerMetadata &) const = default;
};
// Explicit incoming display state for LOAD_BATTLE_BG. Four-bit artwork is
// generated during loading using the preceding parity/alternate gate. Two-bit
// artwork is first generated by the next logical tick and retains its incoming
// scroll until then. A fresh controller can use these zero-initialized values.
struct BattleBackgroundStart {
  unsigned frame_parity{};
  bool previous_alternate{}, defeated{};
  BattleBackgroundTick::Scroll primary_scroll{}, secondary_scroll{}, effects{};
  BattleBackgroundBlend inherited_blend = BattleBackgroundBlend::Opaque;
  std::uint16_t reflect_duration{}, green_background_duration{};
  PaletteColor backdrop{};
  // A loader with no second layer disables it without clearing its retained
  // palette. Transfer this value from the preceding scene when replacing it;
  // the zero default represents a fresh, explicitly cold scene owner.
  BattleBackgroundPalette retained_secondary_palette;
  std::optional<BattleBackground> retained_secondary_background;
  BattleBackgroundLayerMetadata retained_secondary_metadata;
  // MEMSET16 clears only118 of each119-byte loaded record. The high byte
  // of compression acceleration survives until a real distortion overwrites it.
  std::uint8_t primary_compression_acceleration_high{}, secondary_compression_acceleration_high{};
  BattleDistortionAxis primary_axis{}, secondary_axis{};
  std::array<std::uint16_t, 224> primary_offsets{}, secondary_offsets{};

};
struct BattleBackgroundEffects {
  bool darkening{}, opening_letterbox{};
  std::uint16_t brightness = 0xffff;
  std::uint16_t reflect_duration{}, green_background_duration{};
  std::uint16_t vertical_duration{}, vertical_hold{}, wobble_duration{},
      shake_duration{}, minimum_wait{}, red_duration{}, green_duration{};
  std::uint16_t horizontal_offset{}, vertical_offset{};
  unsigned top_end{}, bottom_start = 224;
  std::uint16_t opening_top = 0x7000, opening_bottom = 0x7000;
  PaletteColor backdrop{}, addition{};
  bool additive_flash{};
  bool operator==(const BattleBackgroundEffects &) const = default;
};
struct BattleBackgroundSceneTick {
  unsigned frame_parity{};
  bool defeated{};
};
struct BattleBackgroundSceneFrame {
  BattleBackgroundPair pair;
  BattleBackgroundFrame primary;
  std::optional<BattleBackgroundFrame> secondary;
  bool shared_artwork{}, secondary_main{};
  BattleBackgroundBlend blend{};
  BattleBackgroundEffects effects;
  unsigned bitdepth = 4;
  std::optional<BattleBackgroundArtworkDependency> retained_artwork{};
  // Native background-only scene. Enemy artwork, PSI, UI and the independent
  // swirl controller are composed by their owners. Sampling never advances
  // time.
  PaletteColor sample(int x, unsigned y) const;
  std::shared_ptr<const DirectSceneFrame>
  draw(unsigned width = 256, std::uint64_t frame = 0,
       std::uint64_t identity = 0) const;
  // Individual source layers with their current offsets and displayed colors.
  // No half-add or flash is baked in. The compositor supplies the real display
  // policy once, and may replace BG1 with the published PSI plane.
  std::shared_ptr<const DirectSceneFrame>
  draw_layers(const ScenePalette &displayed, unsigned width = 256,
              std::uint64_t frame = 0, std::uint64_t identity = 0) const;
  // Read physical published VRAM using the actual BGMODE/BGxSC/BGxNBA
  // mirrors. Retained tiles, map aliases and priority bits belong to this
  // display, not to the immutable compressed-artwork catalog.
  std::shared_ptr<const DirectSceneFrame>
  draw_published_layers(const ScenePalette &, std::span<const std::uint8_t, 65536>,
                        const battle::BackgroundDisplayState &, unsigned width = 256,
                        std::uint64_t frame = 0, std::uint64_t identity = 0) const;
};
class BattleBackgroundScenes;
class BattleBackgroundScene {
public:
  BattleBackgroundSceneFrame snapshot() const;
  // The loader binds these stable borrowed owners. They must outlive the
  // scene and its publisher. A foreign display is rejected before capture.
  const battle::BackgroundDisplayState *
  display_layout(const battle::PsiDisplayState &) const;
  const BattleBackgroundEffects &effects() const { return effects_; }
  const BattleBackground &primary() const { return primary_; }
  const std::optional<BattleBackground> &secondary() const {
    return secondary_;
  }
  bool alternate_distortion() const { return alternate_; }
  void advance(BattleBackgroundSceneTick);
  // C2DB3F phases. The battle frame interleaves real object, PSI, window,
  // swirl and palette owners between these phases; all timers remain here.
  void advance_effects(battle::PaletteBankState *publication = nullptr);
  std::array<BattleBackgroundUpdate, 2> advance_backgrounds(BattleBackgroundSceneTick,
                           battle::PaletteBankState *publication = nullptr);
  void advance_flashes();
  void advance_letterbox();
  void swap_final_distortion() { primary_.swap_final_distortion(); }
  void darken() { effects_.darkening = true; }
  void open_letterbox() { effects_.opening_letterbox = true; }
  void reflect(std::uint16_t duration) { effects_.reflect_duration = duration; }
  void green_background(std::uint16_t duration) {
    effects_.green_background_duration = duration;
  }
  void shake(std::uint16_t duration) { effects_.shake_duration = duration; }
  void wobble(std::uint16_t duration) { effects_.wobble_duration = duration; }
  void quake(unsigned duration, std::uint16_t hold = 0);
  void wait(std::uint16_t duration) { effects_.minimum_wait = duration; }
  void flash_red(std::uint16_t duration) { effects_.red_duration = duration; }
  void flash_green(std::uint16_t duration) {
    effects_.green_duration = duration;
  }
  void apply_palette_brightness(std::uint16_t factor);
  BattleBackgroundPalette retained_secondary_palette() const;
  std::optional<BattleBackground> retained_secondary_background() const;
  const BattleBackgroundLayerMetadata &layer_metadata(unsigned ordinal) const;
  bool can_brighten_inactive_secondary() const noexcept;


  std::optional<BattlePaletteDependency> palette_restoration_dependency() const;
  // The persistent session owns zeroed loaded records until its actual LOAD.
  // A prepared catalog scene is not evidence that that source caller ran.
  void initialize_unloaded_record();
  bool has_loaded_record() const noexcept { return loaded_record_; }
  // Complete ordinary C2DE96: restore both palette bases and the active
  // publication slots, including index0, without ticking any controller.
  // A shared-artwork reset dependency rejects before these mutations.
  void restore_palette(ScenePalette &);
  void restore_palette(battle::PaletteBankState &);
  void restore_palette(battle::PaletteBankState &, BattleSceneFrameReset &);
  // Complete ordinary C2DE0F, including the inactive secondary working base.
  // These stage palette writes only; they do not request or complete a
  // transfer.
  void halve_palette(ScenePalette &);
  void halve_palette(battle::PaletteBankState &);

private:
  void restore_palette_bases();
  bool loaded_record_ = true;
  friend class BattleBackgroundScenes;
  friend class battle::BackgroundLoader;
  void bind_display(const battle::PsiDisplayState &,
                    const battle::BackgroundDisplayState &);
  struct Content;
  BattleBackgroundScene(std::shared_ptr<const Content>, BattleBackgroundPair,
                        BattleBackgroundStart);
  void apply_palette_brightness(std::uint16_t, battle::PaletteBankState *);
  std::shared_ptr<const Content> content_;
  BattleBackgroundPair pair_;
  BattleBackground primary_;
  std::optional<BattleBackground> secondary_;
  BattleBackgroundPalette inactive_secondary_palette_;
  std::optional<BattleBackground> inactive_secondary_background_;
  std::array<BattleBackgroundLayerMetadata, 2> layer_metadata_{};

  BattleBackgroundBlend blend_{};
  BattleBackgroundEffects effects_;
  bool shared_artwork_{}, alternate_{};
  std::optional<BattleBackgroundArtworkDependency> retained_artwork_;
  const battle::PsiDisplayState *display_{};
  const battle::BackgroundDisplayState *display_layout_{};
};
class BattleBackgroundScenes {
public:
  BattleBackgroundScenes(std::span<const std::uint8_t>, GameVersion);
  unsigned size() const;
  GameVersion version() const;
  const BattleBackgrounds &layers() const;

  BattleBackgroundPair selection(unsigned battle) const;
  // Referenced artwork beyond the authored load is supplied by a
  // separate controller. Preparation rejects it until that owner is ported.
  std::optional<BattleBackgroundArtworkDependency> artwork_dependency(
      BattleBackgroundPair,
      BattleArtworkPublication = BattleArtworkPublication::Ordinary) const;
  // The battle selector supplies the extended prayer publication for group478.
  // Explicit pair callers must pass that context themselves.
  BattleBackgroundScene prepare(unsigned battle,
                                BattleBackgroundStart = {}) const;
  BattleBackgroundScene prepare(
      BattleBackgroundPair, BattleBackgroundStart = {},
      BattleArtworkPublication = BattleArtworkPublication::Ordinary) const;

private:
  friend class battle::BackgroundLoader;
  BattleBackgroundScene prepare_impl(BattleBackgroundPair, BattleBackgroundStart,
                                     BattleArtworkPublication, bool published) const;
  std::shared_ptr<const BattleBackgroundScene::Content> content_;
};
} // namespace eb::native
