// Complete original WINDOW_TICK / C12E42 / C1004E reference. Regional PCs and
// data offsets below are independently read from linked source metadata. RAND,
// HP/PP arithmetic, window/meter drawing, status/palette and DMA publication
// execute their actual original bodies. The initial external seams are actor
// pumping, world-screen update, frame completion, battle work and sound. No
// expected image is generated by a CPU-free production renderer.
#include "eb/asset_store.hpp"
#include "eb/main_cpu_65816.hpp"
#include "eb/snes_bus.hpp"
#include "generated_assets.hpp"
#include "eb/native/dialogue/window_host.hpp"
#include "eb/native/dialogue/window_graphics.hpp"
#include "eb/native/party/meter_windows.hpp"
#include "eb/native/story/random.hpp"
#include "eb/native/story/ticks.hpp"
#include <algorithm>
#include <array>
#include <cstdint>
#include <functional>
#include <iostream>
#include <memory>
#include <optional>
#include <span>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
void require(bool value,const std::string& message) {if(!value)throw std::runtime_error(message);}
struct Layout {
    unsigned tick,input_tick,world,random,roller,meter_update,status,palette,animate,publish,meter_publish;
    unsigned actors,screen,wait,battle,oam,create,draw,draw_all,load,chosen_init,show,hide;
    unsigned scene,windows,record_size,open,head,tail,focus,game,flavor,characters,stride;
    unsigned render,mask,selected,dirty,upload,cache,transitions,instant,redraw,early,battle_flag;
    unsigned half,fastest,disabled,flipout,hp_speed,chosen,buffer;
};
Layout layout(eb::GameVersion v) {
    if(v==eb::GameVersion::US)return {
        0xc12dd5,0xc12e42,0xc1004e,0xc08e9a,0xc2109f,0xc213ac,0xc1ff2c,0xc47f87,0xc3e450,0xc2038b,0xc1078d,
        0xc09466,0xc08b26,0xc08756,0xc2db3f,0xc088b1,0xc104ee,0xc107af,0xc2087c,0xc47c3f,0xc43317,0xc10a04,0xc10a1d,
        0x7dfe,0x8650,82,0x88e4,0x88e0,0x88e2,0x8958,0x97f5,0x1d8,0x99ce,95,
        0x89c9,0x9647,0x89ca,0x9649,0x9624,0xb4a2,0xb4b6,0x9622,0x9623,0x968c,0x9643,
        0x9695,0x9696,0x9697,0x9698,0x9627,0x4dc8,0x8969};
    return {
        0xc13502,0xc1355e,0xc100c4,0xc08e8b,0xc20f3b,0xc2124c,0xc1fcab,0xc45c1a,0xc1004a,0xc2036c,0xc10974,
        0xc09445,0xc08b17,0xc0874c,0xc2dab4,0xc088a3,0xc106e4,0xc10996,0xc2081d,0xc459ab,0xc43090,0xc10e5a,0xc10e72,
        0x8176,0x89c2,76,0x8c26,0x8c22,0x8c24,0x8c96,0x9aa9,0x1d5,0x9c7f,94,
        0x8d07,0x993f,0x8d08,0x9941,0x991c,0xb676,0xb68a,0x991a,0x991b,0,0x993b,
        0x9949,0x994a,0x994b,0x994c,0x991f,0x514e,0x8ca7};
}
enum class Entry {Window,World,Core};
enum class Effect {ClearObjects,Actors,Screen,Frame,Battle,Sound};
struct Transfer {unsigned source,destination,length;bool operator==(const Transfer&)const=default;};
struct Counts {
    std::uint64_t instructions{},initialization_instructions{},source_probe_instructions{},source_probe_effects{},source_cases{},matched_cases{},tick_cases{},meter_cases{},lifecycle_cases{},publication_cases{},snapshots{},pixels{},ppu_pixels{},effects{},transfers{},width_checks{};
} counts;
class Source {
  public:
    const eb::GameVersion version;const Layout p;
    std::unique_ptr<eb::SnesBus> bus;eb::MainCpu65816 cpu;
    std::vector<std::string> stages;std::vector<Transfer> transfers;
    std::optional<Effect> pending;bool busy{},recording{};unsigned returning{};
    std::function<void(Effect)> service;
    Source(const eb::GameAssets& assets,unsigned flavor=1):version(assets.version),p(layout(version)),
        bus(std::make_unique<eb::SnesBus>(assets.image,version)),cpu(*bus) {
        const auto initialization_start=counts.instructions;
        cpu.set_runtime(eb::MainCpuRuntime::Legacy);cpu.emulation_mode=false;cpu.status_register=eb::MainCpu65816::InterruptDisable;
        cpu.direct_page=0x1e00;cpu.stack_pointer=0x1fff;cpu.data_bank=0x7e;
        bus->work_ram[0xd]=0x80;bus->write_byte(0x2100,0x80);
        byte(p.game+p.flavor,flavor);
        const bool us=version==eb::GameVersion::US;
        byte(p.game+(us?175:172),4);byte(p.game+(us?121:118),4);
        for(unsigned i=0;i<6;++i) {
            byte(p.game+(us?122:119)+i,i+1);byte(p.game+(us?156:153)+i,i);
            const auto at=p.characters+i*p.stride;
            for(unsigned n=0;n<4;++n)byte(at+n,(us?0x71:0x41)+n);
            if(us)byte(at+4,0);
            put(at+(us?10:9),200);put(at+(us?12:11),100);
            const auto hp=at+(us?67:66);put(hp,1);put(hp+2,100+i);put(hp+4,110+i);
            put(hp+6,1);put(hp+8,50+i);put(hp+10,40+i);
        }
        call(0xc200d9,true);call(p.chosen_init,true);
        for(unsigned i=0;i<6;++i)require(get(p.chosen+i*2)==p.characters+i*p.stride,"C43317 pointer initialization differs");
        require(get(p.focus)==65535 && bus->work_ram[p.render]==0,"C200D9 did not establish hidden empty windows");
        call(p.load,true);
        if(us)call(0xc44963,true,1);
        else {put32(cpu.direct_page+14,0x7f0000);call(0xc08616,true,0,0x3800,0x6000);}
        call(p.palette,true);put(p.selected,65535);put(p.hp_speed,0x8000);put(p.hp_speed+2,0);
        put(2,0);put(0x24,0x1234);put(0x26,0xfedc);put(version==eb::GameVersion::US?0xa50:0xa46,65535);
        stages.clear();transfers.clear();counts.initialization_instructions+=counts.instructions-initialization_start;
    }
    unsigned get(unsigned at)const{return bus->work_ram.at(at)|(unsigned(bus->work_ram.at(at+1))<<8);}
    unsigned get32(unsigned at)const{return get(at)|(get(at+2)<<16);}
    void byte(unsigned at,unsigned value){bus->work_ram.at(at)=std::uint8_t(value);}
    void put(unsigned at,unsigned value){byte(at,value);byte(at+1,value>>8);}
    void put32(unsigned at,unsigned value){put(at,value);put(at+2,value>>16);}
    unsigned slot(unsigned id)const{return get(p.open+id*2);}
    unsigned record(unsigned slot)const{return p.windows+slot*p.record_size;}
    unsigned status_address(unsigned member,unsigned group=0)const{return p.characters+(member-1)*p.stride+(version==eb::GameVersion::US?14:13)+group;}
    void begin(unsigned entry,bool far,unsigned a=0,unsigned x=0,unsigned y=0) {
        require(!busy && !pending,"Original call reentered without a source ABI frame");
        cpu.program_counter=(entry&0xff0000)|0xff00;returning=cpu.program_counter+(far?4:3);
        cpu.status_register=eb::MainCpu65816::InterruptDisable;cpu.accumulator=a;cpu.x_index=x;cpu.y_index=y;
        require(cpu.stack_pointer==0x1fff && cpu.direct_page==0x1e00,"Original caller stack or direct page changed");
        if(far)cpu.execute_instruction<0x22>(entry,4);else cpu.execute_instruction<0x20>(entry&65535,3);
        busy=true;
    }
    void observe(unsigned pc) {
        if(!recording)return;
        const std::array<std::pair<unsigned,const char*>,15> labels{{
            {p.random,"random"},{p.draw,"draw-window"},{p.draw_all,"draw-all"},{p.roller,"roll"},{p.meter_update,"meter-update"},
            {p.status,"status"},{p.palette,"palette"},{p.animate,"palette-animation"},{p.publish,"publish-scene"},
            {p.meter_publish,"publish-meters"},{p.world,"world"},{p.oam,"clear-sprites"},{p.actors,"actors"},{p.screen,"screen"},{p.wait,"frame"}}};
        for(const auto& [address,name]:labels)if(pc==address)stages.emplace_back(name);
        if(pc==p.battle)stages.emplace_back("battle");
        if(pc==0xc08616)transfers.push_back({get32(cpu.direct_page+14),cpu.y_index,cpu.x_index});
        else if(pc==0xc0862e)transfers.push_back({(get(cpu.direct_page+14)<<16)|cpu.y_index,get(cpu.direct_page+16),cpu.x_index});
        if(pc==(version==eb::GameVersion::US?0xc12e23:0xc13541) || pc==(version==eb::GameVersion::US?0xc12e34:0xc13552))
            require(!(cpu.status_register&eb::MainCpu65816::Accumulator8Bit),"Window transitions/dirty operation incorrectly narrowed");
        if(pc==(version==eb::GameVersion::US?0xc12e2b:0xc13549)) {
            require(!(cpu.status_register&eb::MainCpu65816::Accumulator8Bit),"Palette comparison returned narrow from C1FF2C");++counts.width_checks;
        }
        require(pc!=(version==eb::GameVersion::US?0xc12e2d:0xc1354b),"Palette branch incorrectly executed BRK-labelled immediate byte");
    }
    std::optional<Effect> advance() {
        require(!pending,"Original service requires response");
        for(unsigned i=0;i<3000000 && busy;++i) {
            if(cpu.program_counter==returning && cpu.stack_pointer==0x1fff) {
                require(cpu.direct_page==0x1e00 && cpu.data_bank==0x7e,"Original tick changed caller frame");busy=false;return {};
            }
            const auto pc=cpu.program_counter;observe(pc);
            const auto canonical=pc<0xc00000 && pc>=0x808000?pc|0xc00000:pc;
            if(canonical==p.actors+29){pending=Effect::Actors;return pending;}
            if(pc==p.oam || pc==p.screen || pc==p.wait || pc==p.battle || pc==(version==eb::GameVersion::US?0xc0abe0:0xc0abbf)) {
                pending=pc==p.oam?Effect::ClearObjects:pc==p.screen?Effect::Screen:pc==p.wait?Effect::Frame:pc==p.battle?Effect::Battle:Effect::Sound;
                return pending;
            }
            if(version==eb::GameVersion::JP && (pc==0xc439e2 || pc==0xc43be8) && get(0xa031))put(0xa031,0);
            cpu.step_instruction();++counts.instructions;
        }
        require(!busy,"Original tick did not finish: "+cpu.describe_registers());return {};
    }
    void respond() {
        require(bool(pending),"No original service pending");const auto effect=*pending;
        if(service)service(effect);
        if(effect==Effect::Frame)byte(2,(bus->work_ram[2]+1)&255);
        if(effect==Effect::Actors){cpu.step_instruction();++counts.instructions;}
        else if(effect==Effect::ClearObjects){
            const unsigned stack=cpu.stack_pointer,stop=((get(stack+1)+1)&65535)|(unsigned(bus->work_ram[stack+3])<<16);
            for(unsigned n=0;n<2000;++n){cpu.step_instruction();++counts.instructions;if(cpu.program_counter==stop && cpu.stack_pointer==stack+3)break;}
            require(cpu.program_counter==stop && cpu.stack_pointer==stack+3,"OAM_CLEAR failed to return");
        }else cpu.execute_instruction<0x6b>(0,1);pending.reset();if(recording)++counts.effects;
    }

    void drain_publications() {
        // Execute only the real common US/JP IRQ DMA-queue slice. This is an
        // explicit frame-delivery service, not a fabricated full NMI/RTI.
        // Source queue descriptors and live source bytes drive hardware DMA.
        const auto pc=cpu.program_counter;const auto a=cpu.accumulator,x=cpu.x_index,y=cpu.y_index,
            stack=cpu.stack_pointer,direct=cpu.direct_page;
        const auto status=cpu.status_register,bank=cpu.data_bank;
        cpu.program_counter=0xc0823c;cpu.direct_page=0;cpu.data_bank=0;
        cpu.status_register=eb::MainCpu65816::InterruptDisable|eb::MainCpu65816::Index8Bit;
        for(unsigned i=0;i<10000 && cpu.program_counter!=0xc08278;++i){cpu.step_instruction();++counts.instructions;}
        require(cpu.program_counter==0xc08278 && bus->work_ram[0]==bus->work_ram[1],"Original IRQ DMA slice did not drain queue");
        cpu.program_counter=pc;cpu.accumulator=a;cpu.x_index=x;cpu.y_index=y;
        cpu.stack_pointer=stack;cpu.direct_page=direct;cpu.status_register=status;cpu.data_bank=bank;
        put(0x99,0); // Explicit next-frame transfer-budget reset, outside slice.
    }
    void call(unsigned entry,bool far,unsigned a=0,unsigned x=0,unsigned y=0){begin(entry,far,a,x,y);while(advance())respond();}
    void create(unsigned id){call(p.create,false,id);}
    void run(Entry entry) {
        recording=true;stages.clear();transfers.clear();call(entry==Entry::Window?p.tick:entry==Entry::World?p.input_tick:p.world,true);
        counts.transfers+=transfers.size();recording=false;
    }
    unsigned occurrences(const std::string& name)const{return unsigned(std::count(stages.begin(),stages.end(),name));}
};
std::string joined(const std::vector<std::string>& values){std::ostringstream s;for(const auto& value:values){if(s.tellp()>0)s<<',';s<<value;}return s.str();}
struct Case {
    Entry entry=Entry::Window;unsigned windows=0,redraw=0,instant=0,early=0,render=0,mask=0,phase=0,party_id=1;
    unsigned dirty=0,upload=0,disabled_transitions=0,status=0,cache=0,selected=65535,battle=0,fraction=1,concentration=0,scripts_disabled=0,rolling_disabled=0,half=0,fastest=0,flipout=0,hp_speed=0x8000;
};
void configure(Source& source,const Case& c) {
    for(unsigned i=0;i<c.windows;++i)source.create(i+1);
    const bool us=source.version==eb::GameVersion::US;
    source.byte(source.p.redraw,c.redraw);source.byte(source.p.instant,c.instant);if(us)source.byte(source.p.early,c.early);
    source.byte(source.p.render,c.render);source.put(source.p.mask,c.mask);source.put(2,c.phase);source.put(source.p.dirty,c.dirty);
    source.byte(source.p.upload,c.upload);source.put(source.p.transitions,c.disabled_transitions);source.put(source.p.cache,c.cache);
    source.put(source.version==eb::GameVersion::US?0xa60:0xa56,c.scripts_disabled);source.byte(source.p.disabled,c.rolling_disabled);source.byte(source.p.half,c.half);source.byte(source.p.fastest,c.fastest);source.put(source.p.flipout,c.flipout);source.put32(source.p.hp_speed,c.hp_speed);
    source.put(source.p.selected,c.selected);source.put(source.p.battle_flag,c.battle);
    source.byte(source.p.game+(us?122:119)+(c.phase&3),c.party_id);
    source.byte(source.status_address(4),c.status);
    for(unsigned member=1;member<=6;++member){const auto hp=source.p.characters+(member-1)*source.p.stride+(us?67:66);source.put(hp,c.fraction);source.put(hp+6,c.fraction);source.byte(source.status_address(member,4),c.concentration);}
}
void source_case(const eb::GameAssets& assets,const Case& c,unsigned index) {
    Source source(assets);configure(source,c);source.run(c.entry);
    const bool fast=c.entry==Entry::Window && (c.instant || (assets.version==eb::GameVersion::US && c.early));
    require(source.occurrences("random")==unsigned(c.entry==Entry::Window),"Tick entry RNG count differs");
    require(source.occurrences("roll")==unsigned(c.entry!=Entry::Core && !fast),"Tick HP/PP call gate differs");
    require(source.occurrences("meter-update")==unsigned(c.entry!=Entry::Core && !fast),"Tick image-update call gate differs");
    require(source.occurrences("status")==unsigned(c.entry==Entry::Window && !fast && !c.disabled_transitions),"Tick status gate differs");
    require(source.occurrences("palette")==unsigned(c.entry==Entry::Window && !fast && !c.disabled_transitions && c.cache!=unsigned(c.status==1 || c.status==2)),"Status palette gate differs");
    require(source.occurrences("publish-scene")==unsigned(c.entry==Entry::Window && !fast),"Whole scene publication gate differs");
    require(source.occurrences("publish-meters")==unsigned(c.entry==Entry::World && c.dirty),"Meter-area publication gate differs");
    require(source.occurrences("palette-animation")==unsigned(!fast && c.render!=0),"Render-byte palette animation gate differs");
    require(source.occurrences("actors")==unsigned(!fast && !c.battle) && source.occurrences("screen")==unsigned(!fast && !c.battle),"World actor/display order gate differs");
    require(source.occurrences("frame")==unsigned(!fast) && source.occurrences("battle")==unsigned(!fast && c.battle),"World frame/battle branch differs");
    const auto find=[&](const std::string& name){return std::find(source.stages.begin(),source.stages.end(),name)-source.stages.begin();};
    if(!fast && !c.battle)require(find("clear-sprites")<find("actors") && find("actors")<find("screen") && find("screen")<find("frame"),"World original work order differs");
    if(c.entry==Entry::Window && !fast)require(find("roll")<find("meter-update") && find("meter-update")<find("publish-scene") && find("publish-scene")<find("world"),"Window original stage order differs");
    if(c.entry==Entry::World)require(find("roll")<find("meter-update") && find("meter-update")<find("world"),"WorldTick original stage order differs");
    if(!fast && c.entry!=Entry::Core)require(source.get(source.p.dirty)==0,"Window/world tick retained dirty high byte");
    ++counts.source_cases;
    std::cout<<(assets.version==eb::GameVersion::US?"US":"JP")<<" source="<<index<<" stages="<<joined(source.stages)<<" copies="<<source.transfers.size()<<" cache="<<source.get(source.p.cache)<<" dirty="<<source.get(source.p.dirty)<<" upload="<<unsigned(source.bus->work_ram[source.p.upload])<<'\n';
}

namespace dialogue=eb::native::dialogue;
namespace party=eb::native::party;
namespace story=eb::native::story;
unsigned raster(const Source& source,unsigned descriptor,unsigned x,unsigned y) {
    if(descriptor&0x4000)x=7-x;if(descriptor&0x8000)y=7-y;
    const auto address=(0xc000+(descriptor&1023)*16+y*2)&65535;
    const auto color=((source.bus->video_ram[address]>>(7-x))&1)|(((source.bus->video_ram[(address+1)&65535]>>(7-x))&1)<<1);
    return color?color+((descriptor>>10)&7)*4:0;
}
struct Pair {
    Source source;dialogue::State state;party::State members;
    std::shared_ptr<const dialogue::FontResources> fonts;dialogue::TextOutput output;dialogue::WindowHost host;
    std::shared_ptr<dialogue::WindowGraphics> graphics;party::MeterWindows meters;story::RandomState random{0x1234,0xfedc};story::TickState tick_state;story::Ticks ticks;
    std::string context;
    Pair(const eb::GameAssets& assets):source(assets),members(assets.version),fonts(dialogue::FontResources::import(assets.image,assets.version)),
        output(fonts,state),host(dialogue::WindowResources::import(assets.image,assets.version),state,output),
        meters(host,members,party::MeterWindowResources::import(assets.image,assets.version)),ticks(host,members,random,meters,tick_state),context(assets.version==eb::GameVersion::US?"US":"JP") {
        const bool us=assets.version==eb::GameVersion::US;
        graphics=std::make_shared<dialogue::WindowGraphics>(dialogue::WindowInitializationResources::import(assets.image,assets.version),output);host.set_graphics(graphics);
        std::array<std::uint8_t,5> name{std::uint8_t(us?0x71:0x41),std::uint8_t(us?0x72:0x42),std::uint8_t(us?0x73:0x43),std::uint8_t(us?0x74:0x44),0};
        dialogue::PartyNameInputs names;for(auto& entry:names.names)entry=name;
        graphics->prepare(names,1);auto publication=graphics->begin_publication(us?dialogue::ArtworkPublication::GeneratedThenCommon:dialogue::ArtworkPublication::All);
        while(publication->advance()==dialogue::Progress::Suspended)publication->respond();require(publication->complete(),"Native artwork initialization incomplete");
        host.publish_palette(1,false,false);members.controlled_count=4;members.party_count=4;
        members.party_order={1,2,3,4,5,6};members.controlled_order={0,1,2,3,4,5};
        for(unsigned i=0;i<6;++i){auto field=members.name_field(i+1);std::copy_n(name.begin(),field.size(),field.begin());auto& member=members.character(i+1);member.maximum_hp=200;member.maximum_pp=100;member.hp_fraction=1;member.current_hp=100+i;member.target_hp=110+i;member.pp_fraction=1;member.current_pp=50+i;member.target_pp=40+i;}
    }
    void configure(const Case& c) {
        ::configure(source,c);
        for(unsigned i=0;i<c.windows;++i){auto operation=host.begin({dialogue::WindowAction::Open,dialogue::WindowId{i+1}});while(operation->advance()==dialogue::OutputProgress::Suspended)operation->respond();require(operation->complete(),"Native window setup incomplete");}
        if(c.redraw){auto op=meters.begin_show();while(op->advance()==dialogue::OutputProgress::Suspended)op->respond();require(op->complete(),"Native redraw setup incomplete");}else output.acknowledge_redraw();output.policy().instant=c.instant!=0;
        tick_state.frame_counter=std::uint8_t(c.phase);tick_state.disabled_transitions=std::uint16_t(c.disabled_transitions);tick_state.last_controlled_status=std::uint16_t(c.cache);tick_state.action_scripts_disabled=std::uint16_t(c.scripts_disabled);tick_state.hp_speed=c.hp_speed;tick_state.fastest_hp_increase=std::uint8_t(c.fastest);tick_state.flipout=std::uint16_t(c.flipout);host.prompt_state().rolling_disabled=std::uint8_t(c.rolling_disabled);host.prompt_state().half_meter_speed=std::uint8_t(c.half);
        host.menu_state().early_tick_exit=c.early!=0;host.prompt_state().battle_mode=std::uint16_t(c.battle);
        meters.state()={std::uint8_t(c.render),std::uint16_t(c.mask),std::uint16_t(c.selected),std::uint16_t(c.dirty),std::uint8_t(c.upload)};
        members.party_order[c.phase&3]=std::uint8_t(c.party_id);members.character(4).afflictions[0]=std::uint8_t(c.status);
        for(unsigned id=1;id<=6;++id){auto& m=members.character(id);m.hp_fraction=std::uint16_t(c.fraction);m.pp_fraction=std::uint16_t(c.fraction);m.afflictions[4]=std::uint8_t(c.concentration);}
    }
    void compare(const std::string& checkpoint,bool published=true) {
        const auto label=context+" "+checkpoint;const auto& m=meters.state();
        require(m.render==source.bus->work_ram[source.p.render] && m.drawn_mask==source.get(source.p.mask) && m.selected_phase==source.get(source.p.selected) && m.area_dirty==source.get(source.p.dirty) && m.upload==source.bus->work_ram[source.p.upload],label+" meter flags differ");
        const bool us=source.version==eb::GameVersion::US;
        for(unsigned id=1;id<=6;++id){const auto base=source.p.characters+(id-1)*source.p.stride+(us?67:66);const auto& member=members.character(id);const std::array values{member.hp_fraction,member.current_hp,member.target_hp,member.pp_fraction,member.current_pp,member.target_pp};for(unsigned i=0;i<values.size();++i)require(values[i]==source.get(base+i*2),label+" party meter differs");}
        for(unsigned i=0;i<32;++i)require(host.palette()[i]==source.get(0x200+i*2),label+" UI palette differs color="+std::to_string(i));
        const auto scene=host.scene(),frame=host.frame();require(scene->width==256 && scene->height==224 && frame->width==256 && frame->height==224,label+" native scene dimensions differ");
        for(unsigned y=0;y<224;++y)for(unsigned x=0;x<256;++x){const auto at=(y/8)*32+x/8,pixel=y*256+x;const auto descriptor=source.get(source.p.scene+at*2),color=raster(source,descriptor,x%8,y%8);require(scene->pixels[pixel]==color && scene->priority[pixel]==(color?bool(descriptor&0x2000):false),label+" staged pixel="+std::to_string(pixel)+" native="+std::to_string(scene->pixels[pixel])+" source="+std::to_string(color));++counts.pixels;
            if(published){const auto position=0xf800+at*2,word=source.bus->video_ram[position]|unsigned(source.bus->video_ram[position+1])<<8,visible=raster(source,word,x%8,y%8);require(frame->pixels[pixel]==visible && frame->priority[pixel]==(visible?bool(word&0x2000):false),label+" published pixel="+std::to_string(pixel)+" native="+std::to_string(frame->pixels[pixel])+" source="+std::to_string(visible));++counts.pixels;}}
        const auto tail=host.tail_frame();require(tail->width==256 && tail->height==8,label+" tail dimensions differ");
        if(published)for(unsigned y=0;y<8;++y)for(unsigned x=0;x<256;++x){const unsigned cell=x/8,at=0xff00+cell*2,word=source.bus->video_ram[at]|unsigned(source.bus->video_ram[at+1])<<8,color=raster(source,word,x%8,y);require(tail->pixels[y*256+x]==color && tail->priority[y*256+x]==(color?bool(word&0x2000):false),label+" fixed tail differs pixel="+std::to_string(y*256+x));++counts.pixels;}
        ++counts.snapshots;
    }
    void deliver(){while(host.publish_next()){};}
    void compare_ppu() {
        auto display=std::make_unique<eb::SnesBus>(std::span(eb::rom_data(source.version),eb::rom_size(source.version)),source.version);
        display->video_ram=source.bus->video_ram;std::copy_n(source.bus->work_ram.begin()+0x200,64,display->palette_ram.begin());
        display->write_byte(0x2100,15);display->write_byte(0x2105,1);display->write_byte(0x2109,0x7c);display->write_byte(0x210c,6);display->write_byte(0x212c,4);display->write_byte(0x2112,255);display->write_byte(0x2112,255);
        while(display->completed_frames<2)display->advance_cpu_cycles(1000);
        const auto frame=host.frame();const auto expand=[](unsigned v){return(v<<3)|(v>>2);};
        for(unsigned i=0;i<256*224;++i){const auto color=host.palette().at(frame->pixels[i]);const auto rgba=0xff000000u|(expand(color&31)<<16)|(expand((color>>5)&31)<<8)|expand((color>>10)&31);require(display->native_framebuffer[i]==rgba,context+" original software PPU differs at "+std::to_string(i));++counts.ppu_pixels;}
    }
};
void native_meter_cases(const eb::GameAssets& assets) {
    for(unsigned phase=0;phase<4;++phase)for(unsigned selected:{0xffffu,phase})for(unsigned concentration:{0u,1u}) {
        Pair pair(assets);Case c;c.render=1;c.mask=15;c.phase=phase;c.selected=selected;c.concentration=concentration;pair.configure(c);pair.context+=" direct meter phase="+std::to_string(phase);
        pair.source.call(assets.version==eb::GameVersion::US?0xc203c3:0xc203a4,false,phase);pair.meters.draw(phase);pair.compare("draw",false);
        pair.source.call(pair.source.p.publish,true);pair.host.queue_scene();pair.deliver();pair.compare("publish");pair.compare_ppu();
        pair.source.call(pair.source.p.meter_update,true);pair.meters.update(phase);pair.deliver();pair.compare("fraction update");
        ++counts.matched_cases;++counts.meter_cases;
    }
}


void native_publication_cases(const eb::GameAssets& assets) {
    Pair pair(assets);Case c;c.render=1;c.mask=15;pair.configure(c);pair.context+=" retained publication";
    pair.source.byte(0xd,0);pair.source.byte(0,0);pair.source.byte(1,0);pair.source.put(0x99,0);
    pair.source.create(1);auto open=pair.host.begin({dialogue::WindowAction::Open,dialogue::WindowId{1}});while(open->advance()==dialogue::OutputProgress::Suspended)open->respond();
    pair.source.call(pair.source.p.draw_all,true);pair.meters.draw_all();pair.host.draw_windows();
    pair.source.call(pair.source.p.meter_publish,false);pair.host.queue_meter_area();
    require(pair.host.pending_publications()==1 && std::uint8_t(pair.source.bus->work_ram[0]-pair.source.bus->work_ram[1])==8,"Meter-area queue entry count differs");
    pair.compare("before meter-area delivery");pair.source.drain_publications();pair.deliver();pair.compare("meter-area delivery");
    unsigned changed_upper=0;
    for(unsigned cell=0;cell<18*32;++cell){const auto staged=pair.source.get(pair.source.p.scene+cell*2),at=0xf800+cell*2,visible=pair.source.bus->video_ram[at]|unsigned(pair.source.bus->video_ram[at+1])<<8;for(unsigned y=0;y<8;++y)for(unsigned x=0;x<8;++x)changed_upper+=raster(pair.source,staged,x,y)!=raster(pair.source,visible,x,y);}
    require(changed_upper>0,"Meter-only publication did not leave a meaningfully different upper window staged");
    const auto held=pair.host.frame();const auto held_pixels=held->pixels;
    pair.source.call(pair.source.p.publish,true);pair.host.queue_scene();require(pair.host.pending_publications()==2,"Scene/fixed-tail publication collapsed ordering");
    auto& member=pair.members.character(1);member.current_hp=987;member.current_pp=321;
    const unsigned base=pair.source.p.characters+(assets.version==eb::GameVersion::US?67:66);
    pair.source.put(base+2,987);pair.source.put(base+8,321);
    pair.source.call(assets.version==eb::GameVersion::US?0xc203c3:0xc203a4,false,0);pair.meters.draw(0);
    pair.compare("changed staging before scene delivery");pair.source.drain_publications();pair.deliver();pair.compare("live scene and tail delivered");
    require(held->pixels==held_pixels,"Held native frame changed after deferred publication");
    // Two queued strip updates retain the live twelve-cell buffer. A later
    // complete draw changes that buffer before either queued set is delivered.
    pair.source.call(pair.source.p.meter_update,true);pair.meters.update(0);
    member.current_hp=654;member.current_pp=210;pair.source.put(base+2,654);pair.source.put(base+8,210);
    pair.source.call(pair.source.p.meter_update,true);pair.meters.update(0);
    require(pair.host.pending_publications()==8 && std::uint8_t(pair.source.bus->work_ram[0]-pair.source.bus->work_ram[1])==64,"Repeated meter strip queue count differs");
    member.current_hp=246;member.current_pp=135;pair.source.put(base+2,246);pair.source.put(base+8,135);
    pair.source.call(assets.version==eb::GameVersion::US?0xc203c3:0xc203a4,false,0);pair.meters.draw(0);
    pair.compare("live digit buffer pending");pair.source.drain_publications();pair.deliver();pair.compare("live digit strips delivered");pair.compare_ppu();++counts.matched_cases;++counts.publication_cases;
}
void native_lifecycle_cases(const eb::GameAssets& assets) {
    for(unsigned phase=0;phase<4;++phase)for(bool battle:{false,true}) {
        Pair pair(assets);Case c;c.render=1;c.mask=15;c.selected=phase;c.battle=battle;pair.configure(c);pair.context+=" lifecycle phase="+std::to_string(phase)+" battle="+std::to_string(battle);
        pair.source.call(assets.version==eb::GameVersion::US?0xc2077d:0xc2071e,false);pair.meters.draw_all();
        pair.source.call(pair.source.p.publish,true);pair.host.queue_scene();pair.deliver();pair.compare("visible before hide");
        pair.source.call(pair.source.p.hide,false);auto hide=pair.meters.begin_hide(battle);unsigned waits=0;while(hide->advance()==dialogue::OutputProgress::Suspended){require(hide->effect()->kind==dialogue::WindowEffectKind::FrameWait,"Meter hide emitted non-frame effect");++waits;hide->respond();}
        require(hide->complete() && waits==unsigned(assets.version==eb::GameVersion::US),"Regional meter-clear frame cadence differs");
        pair.compare("hidden staging");pair.source.call(pair.source.p.publish,true);pair.host.queue_scene();pair.deliver();pair.compare("hidden publication");
        pair.source.call(pair.source.p.show,false);auto show=pair.meters.begin_show();while(show->advance()==dialogue::OutputProgress::Suspended)show->respond();require(show->complete(),"Meter show incomplete");
        pair.source.call(pair.source.p.draw_all,true);pair.meters.draw_all();pair.host.draw_windows();pair.source.call(pair.source.p.publish,true);pair.host.queue_scene();pair.deliver();pair.compare("shown again");pair.compare_ppu();++counts.matched_cases;++counts.lifecycle_cases;
    }
}
void native_tick_case(const eb::GameAssets& assets,const Case& c,unsigned index) {
    Pair pair(assets);pair.configure(c);pair.context+=" tick case="+std::to_string(index);
    pair.source.byte(0xd,0);pair.source.byte(0,0);pair.source.byte(1,0);pair.source.put(0x99,0);
    pair.source.recording=true;pair.source.stages.clear();pair.source.transfers.clear();
    pair.source.begin(c.entry==Entry::Window?pair.source.p.tick:c.entry==Entry::World?pair.source.p.input_tick:pair.source.p.world,true);
    auto operation=pair.ticks.begin(c.entry==Entry::Window?story::TickKind::Window:c.entry==Entry::World?story::TickKind::World:story::TickKind::WorldFrame);
    unsigned service_index=0;
    const auto compare_state=[&]{
        pair.compare("service="+std::to_string(service_index));
        require(pair.random.primary_word==pair.source.get(0x24) && pair.random.secondary_word==pair.source.get(0x26),pair.context+" RNG words differ");
        require(pair.tick_state.last_controlled_status==pair.source.get(pair.source.p.cache),pair.context+" status cache differs");
        require(pair.tick_state.action_scripts_disabled==pair.source.get(assets.version==eb::GameVersion::US?0xa60:0xa56),pair.context+" actor guard differs");
        require(pair.tick_state.frame_counter==pair.source.bus->work_ram[2],pair.context+" frame byte differs");
        if(assets.version==eb::GameVersion::US)require(pair.host.menu_state().early_tick_exit==bool(pair.source.bus->work_ram[pair.source.p.early]),pair.context+" early exit byte differs");
        require(pair.output.redraw_pending()==bool(pair.source.bus->work_ram[pair.source.p.redraw]),pair.context+" redraw flag differs");
    };
    for(unsigned budget_round=0;budget_round<1000;++budget_round) {
        const auto progress=operation->advance(index%3==0?1:index%3==1?7:4096);if(progress==dialogue::Progress::BudgetExhausted)continue;
        const auto expected=pair.source.advance();compare_state();
        if(progress==dialogue::Progress::Finished){require(!expected && !pair.source.busy,pair.context+" native completed before original");break;}
        require(expected.has_value(),pair.context+" native emitted an extra service");const auto service=*operation->service();
        const auto actual=service==story::TickService::ClearObjects?Effect::ClearObjects:service==story::TickService::RunActors?Effect::Actors:service==story::TickService::UpdateScreen?Effect::Screen:service==story::TickService::FrameBoundary?Effect::Frame:Effect::Battle;
        require(actual==*expected,pair.context+" service order differs at "+std::to_string(service_index));
        if(actual==Effect::Frame){pair.source.drain_publications();pair.deliver();pair.compare("frame delivery");++pair.tick_state.frame_counter;}
        pair.source.respond();operation->respond();++service_index;
    }
    require(operation->complete() && !pair.source.busy,pair.context+" tick budget failed to finish");
    pair.compare_ppu();++counts.matched_cases;++counts.tick_cases;
}
std::vector<Case> corpus() {
    std::vector<Case> result;
    for(auto entry:{Entry::Window,Entry::World,Entry::Core})for(unsigned open:{0u,1u,2u})for(unsigned redraw:{0u,1u}){Case c;c.entry=entry;c.windows=open;c.redraw=redraw;result.push_back(c);}
    for(unsigned instant:{0u,1u,255u})for(unsigned early:{0u,1u,255u}){Case c;c.instant=instant;c.early=early;c.windows=2;c.redraw=1;result.push_back(c);}
    for(unsigned status:{0u,1u,2u,3u,255u})for(unsigned disabled:{0u,1u,0x100u,0x8000u,0xffffu})for(unsigned cache:{0u,1u}){Case c;c.status=status;c.disabled_transitions=disabled;c.cache=cache;result.push_back(c);}
    for(auto entry:{Entry::Window,Entry::World,Entry::Core})for(unsigned phase=0;phase<4;++phase)for(unsigned render:{0u,1u})for(unsigned mask:{0u,15u}){Case c;c.entry=entry;c.phase=phase;c.render=render;c.mask=mask;c.selected=phase;result.push_back(c);}
    for(unsigned party:{0u,1u,4u,5u,6u})for(unsigned fraction:{0u,1u,2u,0xffffu})for(unsigned upload:{0u,1u}){Case c;c.entry=Entry::World;c.render=1;c.mask=15;c.party_id=party;c.fraction=fraction;c.upload=upload;c.concentration=1;result.push_back(c);}
    for(auto entry:{Entry::Window,Entry::World,Entry::Core})for(unsigned dirty:{0u,1u,0xa500u})for(unsigned battle:{0u,1u}){Case c;c.entry=entry;c.dirty=dirty;c.battle=battle;c.render=1;c.mask=15;result.push_back(c);}
    for(unsigned disabled:{1u,0x8000u})for(auto entry:{Entry::Window,Entry::World,Entry::Core}){Case c;c.entry=entry;c.scripts_disabled=disabled;result.push_back(c);}
    for(unsigned bits=0;bits<8;++bits){Case c;c.entry=Entry::World;c.phase=0xa5ff;c.render=1;c.mask=15;c.rolling_disabled=bits&1;c.half=bits&2;c.fastest=bits&4;c.hp_speed=0x18000;result.push_back(c);}
    return result;
}
}
int main(int argc,char** argv) {
    if(argc<2){std::cout<<"SKIP: local US/JP asset packs are required for original tick artwork\n";return 77;}
    try {
        for(int arg=1;arg<argc;++arg) {
            const auto assets=eb::load_game_assets(argv[arg],eb::asset_profiles());unsigned index=0;
            const auto probe_start=counts.instructions,probe_effects=counts.effects;for(const auto& test:corpus())source_case(assets,test,index++);counts.source_probe_instructions+=counts.instructions-probe_start;counts.source_probe_effects+=counts.effects-probe_effects;native_meter_cases(assets);native_publication_cases(assets);native_lifecycle_cases(assets);index=0;for(const auto& test:corpus())native_tick_case(assets,test,index++);
        }
        require(counts.matched_cases==counts.tick_cases+counts.meter_cases+counts.lifecycle_cases+counts.publication_cases,"Native corpus counter sum differs");
        std::cout<<"PASS original tick probes: "<<counts.source_cases<<" cases, "<<counts.source_probe_instructions<<" source-only instructions including initialization, "<<counts.source_probe_effects<<" external boundaries, "<<counts.transfers<<" transfer entries\n";
        std::cout<<"Native tick/meter: "<<counts.matched_cases<<" cases ("<<counts.tick_cases<<" complete ticks, "<<counts.meter_cases<<" direct meters, "<<counts.lifecycle_cases<<" lifecycles, "<<counts.publication_cases<<" deferred publications), "<<counts.snapshots<<" snapshots, "<<counts.pixels<<" indexed pixels, "<<counts.ppu_pixels<<" software-PPU pixels, "<<counts.effects-counts.source_probe_effects<<" matched service boundaries\n";
        std::cout<<"Original execution: "<<counts.instructions<<" instructions across source-only/matched cases/setup/delivery, "<<counts.initialization_instructions<<" within source constructors, "<<counts.width_checks<<" accumulator16 comparison paths\n";
        std::cout<<"Scope: complete original/native window/world tick wrappers; actual original RAND, roller, meter/window/palette bodies and queued copies. The original IRQ DMA-queue slice completes publications at the explicit frame service. Empty-entity actor prologue/epilogue and OAM clear execute; actor work, screen refresh, frame/input completion, battle and sound remain named services. Direct meter helpers also use forced-blank original DMA. No full NMI scheduling, PCM, populated ActorWorld or GPU proof.\n";
    } catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}
}
