// Independent absent-focus text oracle. Original code, frame setup, glyphs,
// close and scroll all execute through Legacy CPU. Expected artwork is decoded
// only from original WRAM/VRAM. Host sound/tick and completed JP DMA are explicit
// boundaries; no expected pixel is generated by the native text implementation.
// JP only: OPEN_WINDOW_TABLE indexed by $fffe resolves to $7f8c24, not the
// adjacent WINDOW_TAIL word in bank $7e. Fixture input explicitly supplies the
// same physical ambient slot to both implementations. LOAD_WINDOW_GFX,
// CREATE/CLOSE_WINDOW, PRINT_LETTER, PRINT_NEWLINE and DISPLAY_TEXT execute
// their unchanged source bodies. WINDOW_TICK, PLAY_SOUND and frame wait return
// at declared external host seams; callbacks perform real source calls with
// separate DP locals and preserve the suspended caller's locals/return stack.
// Forced-blank DMA executes normally. Only its already-completed JP semaphore
// is acknowledged before C439E2/C43BE8, without running an unrelated NMI loop.
// Canvas expectations decode actual source descriptors and VRAM; scene checks
// use the original PPU renderer. They do not prove a full world/audio scheduler.
#include "eb/asset_store.hpp"
#include "eb/main_cpu_65816.hpp"
#include "eb/snes_bus.hpp"
#include "generated_assets.hpp"
#include "eb/native/dialogue/fonts.hpp"
#include "eb/native/dialogue/window_graphics.hpp"
#include "eb/native/dialogue/conversation.hpp"
#include <algorithm>
#include <array>
#include <cstdint>
#include <functional>
#include <iostream>
#include <memory>
#include <span>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
namespace {
void require(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
std::string hex(unsigned value){std::ostringstream out;out<<std::hex<<value;return out.str();}
struct Totals {std::uint64_t steps{},calls{},ticks{},sounds{},dma_acknowledgements{},writes{},canvas_pixels{},brush_pixels{},publication_pixels{},ppu_pixels{};unsigned cases{},native_cases{},comparisons{},native_effects{},complete_streams{},nested_lifecycles{};} totals;
struct Image {unsigned width{},height{};std::vector<std::uint8_t> pixels,priority;bool operator==(const Image&)const=default;};
struct State {
    unsigned x{},y{},font{},attributes{},focus{},head{},tail{},redraw{},saturn{},brush_x{},brush_column{},publication{};
    std::array<std::array<std::uint8_t,128>,4> brush{};
    std::array<std::array<std::uint8_t,128>,48> artwork{};
    std::vector<std::uint16_t> descriptors;
    Image canvas;
};
struct Write {unsigned address{},value{};};
class Original {
 public:
    std::unique_ptr<eb::SnesBus> bus;eb::MainCpu65816 cpu;
    std::function<void(unsigned)> at_instruction,at_service;
    std::vector<Write> writes;
    bool observe{};
    explicit Original(const eb::GameAssets& assets):bus(std::make_unique<eb::SnesBus>(assets.image,assets.version)),cpu(*bus) {
        require(assets.version==eb::GameVersion::JP,"Absent-focus source corpus requires JP assets");
        cpu.set_runtime(eb::MainCpuRuntime::Legacy);cpu.emulation_mode=false;cpu.direct_page=0x1e00;cpu.stack_pointer=0x1fff;cpu.data_bank=0x7e;cpu.status_register=eb::MainCpu65816::InterruptDisable;
        bus->work_ram[0xd]=0x80;bus->write_byte(0x2100,0x80);call(0xc200d9,true);call(0xc43be8,true);
        bus->work_ram[0x9c7e]=1;
        for(unsigned member=0;member<4;++member)for(unsigned i=0;i<4;++i)bus->work_ram[0x9c7f+member*94+i]=0x41+i;
        call(0xc459ab,true);put32(0x1e0e,0x7f0000);call(0xc08616,true,0,0x3800,0x6000);open(1);
        bus->work_ram[0x991a]=1;
        cpu.observe_memory_write=[&](std::uint32_t at,std::uint8_t value){if(observe && (at>>16)==0x7e){writes.push_back({at&65535,value});++totals.writes;}};
    }
    unsigned get(unsigned at)const{return bus->work_ram.at(at)|(unsigned(bus->work_ram.at(at+1))<<8);}
    void put(unsigned at,unsigned value){bus->work_ram.at(at)=value;bus->work_ram.at(at+1)=value>>8;}
    void put32(unsigned at,unsigned value){put(at,value);put(at+2,value>>16);}
    unsigned record(unsigned slot)const{require(slot<8,"Invalid source physical slot");return 0x89c2+slot*76;}
    unsigned slot(unsigned id)const{const unsigned result=get(0x8c26+id*2);require(result<8,"Source window not open");return result;}
    void call(unsigned entry,bool far,unsigned a=0,unsigned x=0,unsigned y=0) {
        const unsigned d=cpu.direct_page,s=cpu.stack_pointer,db=cpu.data_bank,target=(entry&0xff0000)|0xff00;
        cpu.program_counter=target;cpu.accumulator=a;cpu.x_index=x;cpu.y_index=y;cpu.status_register=eb::MainCpu65816::InterruptDisable;
        if(far)cpu.execute_instruction<0x22>(entry,4);else cpu.execute_instruction<0x20>(entry&65535,3);++totals.calls;
        for(unsigned n=0;n<3000000;++n) {
            if(cpu.program_counter==target+(far?4:3) && cpu.stack_pointer==s){require(cpu.direct_page==d && cpu.data_bank==db,"Source caller ABI changed");return;}
            const auto pc=cpu.program_counter;if(at_instruction)at_instruction(pc);
            if(pc==0xc07eab && at_service)at_service(pc); // Observe actual party-blink helper; execute its body.
            if(pc==0xc13502 || pc==0xc0abbf || pc==0xc0874c) {
                if(at_service)at_service(pc);if(pc==0xc13502)++totals.ticks;else if(pc==0xc0abbf)++totals.sounds;
                cpu.execute_instruction<0x6b>(0,1);continue;
            }
            if((pc==0xc439e2 || pc==0xc43be8) && get(0xa031)){put(0xa031,0);++totals.dma_acknowledgements;}
            cpu.step_instruction();++totals.steps;
        }
        throw std::runtime_error("Source routine failed to return: "+cpu.describe_registers());
    }
    void nested(unsigned entry,bool far,unsigned argument) {
        const unsigned pc=cpu.program_counter,d=cpu.direct_page,s=cpu.stack_pointer;require(pc==0xc13502,"Source callback must be WindowTick");
        const std::vector<std::uint8_t> locals(bus->work_ram.begin()+d,bus->work_ram.begin()+0x1e12),stack(bus->work_ram.begin()+s+1,bus->work_ram.begin()+0x2000);
        cpu.execute_instruction<0xc2>(0x31,2);cpu.execute_instruction<0x0b>(0,1);cpu.execute_instruction<0x7b>(0,1);cpu.execute_instruction<0x69>(0xffee,3);cpu.execute_instruction<0x5b>(0,1);
        call(entry,far,argument);cpu.execute_instruction<0x2b>(0,1);require(cpu.direct_page==d && cpu.stack_pointer==s && std::equal(locals.begin(),locals.end(),bus->work_ram.begin()+d) &&
            std::equal(stack.begin(),stack.end(),bus->work_ram.begin()+s+1),"Original callback changed parent locals/stack");cpu.program_counter=pc;
    }
    void open(unsigned id){call(0xc106e4,false,id);}
    void close(unsigned id){call(0xc10141,false,id);}
    void focus(unsigned id){put(0x8c96,id);}
    void absent(unsigned slot){put(0x8c96,0xffff);put(0x18c24,slot);}
    void font(unsigned slot,unsigned value){put(record(slot)+21,value);}
    void cursor(unsigned x,unsigned y){call(0xc11169,false,x,y);}
    void print(unsigned code){call(0xc111ec,false,code);}
    void newline(){call(0xc11174,false);}
    void fill(unsigned id) {
        focus(id);const auto at=record(slot(id));font(slot(id),0);
        const unsigned width=get(at+10),lines=get(at+12)/2;
        for(unsigned line=0;line<lines;++line){cursor(0,line);for(unsigned column=0;column<width;++column)print(0x41+(line*3+column)%24);}
        cursor(0,0);
    }
    static unsigned pixel(std::span<const std::uint8_t> bytes,unsigned at,unsigned x,unsigned y){return ((bytes[at+y*2]>>(7-x))&1)|(((bytes[at+y*2+1]>>(7-x))&1)<<1);}
    Image canvas(unsigned slot)const {
        const auto at=record(slot),width=get(at+10),height=get(at+12),tilemap=get(at+53);Image result{width*8,height*8};result.pixels.resize(result.width*result.height);result.priority.resize(result.pixels.size());
        for(unsigned y=0;y<result.height;++y)for(unsigned x=0;x<result.width;++x) {
            const unsigned desc=get(tilemap+((y/8)*width+x/8)*2),gx=desc&0x4000?7-x%8:x%8,gy=desc&0x8000?7-y%8:y%8;
            const auto color=pixel(bus->video_ram,(0xc000+(desc&1023)*16)&65535,gx,gy),index=y*result.width+x;result.pixels[index]=color?color+((desc>>10)&7)*4:0;result.priority[index]=color?bool(desc&0x2000):false;
        }return result;
    }
    void draw_scene() {call(0xc2081d,true);put32(cpu.direct_page+14,0x7e8176);call(0xc08616,true,0,0x800,0x7c00);}
    std::vector<std::uint32_t> ppu()const {
        auto display=std::make_unique<eb::SnesBus>(std::span(eb::rom_data(eb::GameVersion::JP),eb::rom_size(eb::GameVersion::JP)),eb::GameVersion::JP);display->video_ram=bus->video_ram;
        for(unsigned i=0;i<32;++i){const unsigned color=(i*0x421)&0x7fff;display->palette_ram[i*2]=color;display->palette_ram[i*2+1]=color>>8;}
        display->write_byte(0x2100,15);display->write_byte(0x2105,1);display->write_byte(0x2109,0x7c);display->write_byte(0x210c,6);display->write_byte(0x212c,4);display->write_byte(0x2112,0xff);display->write_byte(0x2112,0xff);
        while(display->completed_frames<2)display->advance_cpu_cycles(1000);return {display->native_framebuffer.begin(),display->native_framebuffer.end()};
    }
    State state(unsigned slot)const {
        const auto at=record(slot);State result{get(at+14),get(at+16),get(at+21),get(at+19),get(0x8c96),get(0x8c22),get(0x8c24),bus->work_ram[0x991b],get(0xa02f),get(0xa029),get(0xa02b),get(0xa02d)};
        const auto width=get(at+10),height=get(at+12),tilemap=get(at+53);for(unsigned i=0;i<width*height;++i)result.descriptors.push_back(get(tilemap+i*2));
        for(unsigned column=0;column<4;++column)for(unsigned y=0;y<16;++y)for(unsigned x=0;x<8;++x)result.brush[column][y*8+x]=pixel(bus->work_ram,0x9fa9+column*32,x,y);
        for(unsigned column=0;column<48;++column)for(unsigned y=0;y<16;++y)for(unsigned x=0;x<8;++x) {
            const auto upper=0xf200+(column&15)*16+(column&0x30)*32,at=upper+(y/8)*256;result.artwork[column][y*8+x]=pixel(bus->video_ram,at,x,y%8);
        }
        result.canvas=canvas(slot);return result;
    }
};
unsigned differences(const Image& a,const Image& b){require(a.width==b.width && a.height==b.height,"Image geometry changed");unsigned count=0;for(unsigned i=0;i<a.pixels.size();++i)if(a.pixels[i]!=b.pixels[i] || a.priority[i]!=b.priority[i])++count;return count;}
void source_domains(const eb::GameAssets& assets) {
    for(unsigned retired:{0u,1u})for(unsigned font:{0u,1u})for(unsigned x:{0u,14u,15u})for(unsigned code:{0x41u,0x63u,0x6bu,0x20u,0x1au,0x14fu}) {
        Original source(assets);source.fill(1);const unsigned selected=source.slot(1);source.font(selected,font);source.cursor(x,0);if(retired)source.close(1);source.absent(selected);
        source.bus->work_ram[0x991a]=0;source.put(0x991d,1);source.put(0x9947,2);source.bus->work_ram[0x991b]=0;
        const auto before=source.state(selected);unsigned sounds=0,ticks=0;source.at_service=[&](unsigned pc){if(pc==0xc0abbf)++sounds;if(pc==0xc13502)++ticks;};source.observe=true;source.print(code);source.observe=false;source.at_service={};const auto after=source.state(selected);
        require(after.focus==0xffff && after.head==before.head && after.tail==before.tail,"Absent glyph changed focus/draw order");
        require(ticks==2 && sounds==unsigned(code!=32),"Original absent glyph footer differs");
        if(!font)require(after.x==before.x && after.y==before.y && after.canvas==before.canvas && after.brush==before.brush && after.artwork==before.artwork,"Absent fixed glyph touched canvas/composition");
        std::cout<<"JP "<<(retired?"retired":"live")<<" font="<<font<<" x="<<hex(x)<<" glyph="<<hex(code)<<" -> x="<<hex(after.x)<<" y="<<after.y<<" active="<<after.saturn<<" publication="<<after.publication<<" canvas_pixels="<<differences(before.canvas,after.canvas)<<" effects="<<sounds<<','<<ticks<<'\n';++totals.cases;
    }
    for(unsigned retired:{0u,1u})for(unsigned font:{0u,1u}) {
        Original source(assets);source.fill(1);const auto selected=source.slot(1);source.font(selected,font);source.cursor(7,source.get(source.record(selected)+12)/2-1);
        if(retired)source.close(1);source.absent(selected);const auto before=source.state(selected);source.newline();const auto after=source.state(selected);
        require(after.x==0 && after.y==before.y && after.focus==0xffff,"Original ambient scroll cursor differs");require(differences(before.canvas,after.canvas)>0,"Original ambient scroll did not change retained pixels");
        const unsigned width=source.get(source.record(selected)+10),height=source.get(source.record(selected)+12);
        for(unsigned i=0;i<width*(height-2);++i)require(after.descriptors[i]==before.descriptors[i+width*2],"Original scroll row move differs");
        for(unsigned i=width*(height-2);i<width*height;++i)require(after.descriptors[i]==64,"Original scroll last-row clear differs");
        std::cout<<"JP "<<(retired?"retired":"live")<<" newline font="<<font<<" changed_pixels="<<differences(before.canvas,after.canvas)<<" publication="<<before.publication<<"->"<<after.publication<<'\n';++totals.cases;
    }
}
namespace dialogue=eb::native::dialogue;
struct Pair {
    Original source;
    std::shared_ptr<const dialogue::FontResources> fonts;
    dialogue::State state;
    dialogue::TextOutput output;
    dialogue::WindowHost windows;
    std::shared_ptr<dialogue::WindowGraphics> graphics;
    std::string context="JP";
    std::vector<std::pair<unsigned,State>> events;
    explicit Pair(const eb::GameAssets& assets):source(assets),fonts(dialogue::FontResources::import(assets.image,assets.version)),output(fonts,state),
        windows(dialogue::WindowResources::import(assets.image,assets.version),state,output) {
        graphics=std::make_shared<dialogue::WindowGraphics>(dialogue::WindowInitializationResources::import(assets.image,assets.version),output);windows.set_graphics(graphics);
        const std::array<std::uint8_t,4> name{0x41,0x42,0x43,0x44};dialogue::PartyNameInputs names;for(auto& member:names.names)member=name;graphics->prepare(names,1);
        auto upload=graphics->begin_publication(dialogue::ArtworkPublication::All);while(upload->advance()==dialogue::Progress::Suspended)upload->respond();require(upload->complete(),"Native initial publication incomplete");
        auto create=windows.begin({dialogue::WindowAction::Open,dialogue::WindowId{1}});while(create->advance()==dialogue::OutputProgress::Suspended)create->respond();require(create->complete(),"Native initial window incomplete");
        output.policy().instant=true;compare(source.state(0),0,"initial");
    }
    void compare(const State& expected,unsigned selected,const std::string& where) {
        const auto& actual=windows.slot_output(selected);const auto style=actual.style;
        const unsigned attributes=(style.palette<<10)|(style.priority?0x2000:0)|(style.flip_horizontal?0x4000:0)|(style.flip_vertical?0x8000:0);
        const auto order=windows.draw_order();const auto head=order.empty()?0xffff:*windows.slot_for(order.front()),tail=order.empty()?0xffff:*windows.slot_for(order.back());
        const std::array<unsigned,9> left{actual.cursor.column,actual.cursor.line,style.font,attributes,state.focus?state.focus->value:0xffff,head,tail,unsigned(output.redraw_pending()),unsigned(output.saturn_composition_active())};
        const std::array<unsigned,9> right{expected.x,expected.y,expected.font,expected.attributes,expected.focus,expected.head,expected.tail,expected.redraw,expected.saturn};
        for(unsigned i=0;i<left.size();++i)require(left[i]==right[i],context+" "+where+" metadata["+std::to_string(i)+"] native="+hex(left[i])+" source="+hex(right[i]));
        const auto frame=windows.slot_frame(selected);require(frame->width==expected.canvas.width && frame->height==expected.canvas.height,context+" "+where+" retained extent differs");
        for(unsigned i=0;i<frame->pixels.size();++i){require(frame->pixels[i]==expected.canvas.pixels[i] && frame->priority[i]==expected.canvas.priority[i],context+" "+where+" retained pixel differs "+std::to_string(i));++totals.canvas_pixels;}
        const auto brush=output.composition_snapshot();require(brush.columns.size()==4,context+" JP brush column count differs");
        require(brush.brush_column==expected.brush_column && brush.fractional_offset==(expected.brush_x&7),context+" "+where+" brush cursor differs");
        for(unsigned i=0;i<4;++i)for(unsigned pixel=0;pixel<128;++pixel){require(brush.columns[i][pixel]==expected.brush[i][pixel],context+" "+where+" brush pixels differ column="+std::to_string(i)+" pixel="+std::to_string(pixel)+" native="+std::to_string(brush.columns[i][pixel])+" source="+std::to_string(expected.brush[i][pixel]));++totals.brush_pixels;}
        const auto published=output.publication_snapshot();require(published.current_column==expected.publication,context+" "+where+" publication index differs native="+std::to_string(published.current_column)+" source="+std::to_string(expected.publication));
        for(unsigned i=0;i<48;++i)for(unsigned pixel=0;pixel<128;++pixel){require(published.columns[i][pixel]==expected.artwork[i][pixel],context+" "+where+" publication pixels differ image="+std::to_string(i)+" pixel="+std::to_string(pixel));++totals.publication_pixels;}
        ++totals.comparisons;
    }
    void font(unsigned selected,unsigned value) {
        source.font(selected,value);const auto id=windows.slot(selected).id;require(bool(id),"Set font fixture requires live slot");auto style=output.window(*id).style;style.font=value;output.set_style(*id,style);
    }
    void focus(unsigned id){source.focus(id);state.focus=dialogue::WindowId{id};}
    void absent(unsigned selected){source.absent(selected);state.focus.reset();state.unfocused_register_slot=selected;}
    void cursor(unsigned x,unsigned y) {source.cursor(x,y);require(state.focus.has_value(),"Fixture seed position must be focused");output.set_cursor(*state.focus,{std::uint16_t(x),std::uint16_t(y)});}
    void policy(bool instant,unsigned speed,unsigned sound=2) {
        source.bus->work_ram[0x991a]=instant;source.put(0x991d,speed);source.put(0x9947,sound);
        output.policy().instant=instant;output.policy().text_speed=speed;output.policy().sound_mode=sound;
    }
    void window(dialogue::WindowAction action,unsigned id) {
        if(action==dialogue::WindowAction::Open)source.open(id);else source.close(id);
        auto operation=windows.begin({action,dialogue::WindowId{id}});while(operation->advance()==dialogue::OutputProgress::Suspended)operation->respond();require(operation->complete(),"Native window lifecycle incomplete");
        compare(source.state(0),0,"lifecycle");
    }
    void print(unsigned code,unsigned selected,bool check=true) {
        events.clear();if(check)source.at_service=[&](unsigned pc){events.emplace_back(pc,source.state(selected));};
        source.print(code);source.at_service={};const auto final=source.state(selected);
        output.begin_glyph(std::uint16_t(code));unsigned index=0;
        for(unsigned n=0;n<10000;++n) {
            if(output.advance()==dialogue::OutputProgress::Complete)break;
            if(check){require(index<events.size(),context+" extra native output effect");const auto pc=output.effect()->kind==dialogue::TextEffectKind::TextSound?0xc0abbfu:0xc13502u;
                require(pc==events[index].first,context+" output effect order differs");compare(events[index].second,selected,"glyph effect "+std::to_string(index));++index;}
            output.respond();
        }
        require(output.complete() && (!check || index==events.size()),context+" glyph did not complete");if(check)compare(final,selected,"glyph final");totals.native_effects+=index;
    }
    void fill(unsigned id) {
        focus(id);const auto selected=source.slot(id);font(selected,0);const auto at=source.record(selected),width=source.get(at+10),lines=source.get(at+12)/2;
        for(unsigned line=0;line<lines;++line){cursor(0,line);for(unsigned column=0;column<width;++column)print(0x41+(line*3+column)%24,selected,false);}cursor(0,0);
        compare(source.state(selected),selected,"filled source canvas");
    }
    void newline(unsigned selected) {
        source.newline();output.begin({dialogue::RequestKind::Newline});while(output.advance()==dialogue::OutputProgress::Suspended)throw std::runtime_error("Native newline invented an effect");
        require(output.complete(),"Native newline incomplete");compare(source.state(selected),selected,"newline");
    }
    void scene(bool publish=true) {
        if(publish){source.draw_scene();windows.draw_windows();windows.publish_scene();}
        const auto expected=source.ppu();const auto actual=windows.frame();require(actual->width==256 && actual->height==224,"Native scene extent differs");
        for(unsigned i=0;i<expected.size();++i) {
            const auto expand=[](unsigned v){return(v<<3)|(v>>2);};const unsigned color=(actual->pixels[i]*0x421)&0x7fff;
            const unsigned rgb=0xff000000u|(expand(color&31)<<16)|(expand((color>>5)&31)<<8)|expand((color>>10)&31);
            require(rgb==expected[i],context+" actual original PPU differs "+std::to_string(i));++totals.ppu_pixels;
        }
    }
};
void native_domains(const eb::GameAssets& assets) {
    for(unsigned retired:{0u,1u})for(unsigned font:{0u,1u})for(unsigned x:{0u,14u,15u})for(unsigned code:{0x41u,0x63u,0x6bu,0x20u,0x1au,0x14fu}) {
        Pair pair(assets);pair.context+=" retired="+std::to_string(retired)+" font="+std::to_string(font)+" x="+std::to_string(x)+" code="+hex(code);
        pair.fill(1);pair.font(0,font);pair.cursor(x,0);pair.scene();if(retired)pair.window(dialogue::WindowAction::Close,1);pair.absent(0);pair.policy(false,1);
        pair.print(code,0);pair.scene(false);pair.scene();++totals.native_cases;
    }
    for(unsigned retired:{0u,1u})for(unsigned font:{0u,1u}) {
        Pair pair(assets);pair.context+=" scroll retired="+std::to_string(retired)+" font="+std::to_string(font);pair.fill(1);pair.font(0,font);pair.cursor(7,pair.source.get(pair.source.record(0)+12)/2-1);
        if(retired)pair.window(dialogue::WindowAction::Close,1);pair.absent(0);const auto held=pair.windows.slot_frame(0);const auto held_pixels=held->pixels;
        pair.newline(0);require(held->pixels==held_pixels,"Retained canvas sampling was not immutable");require(pair.windows.slot_frame(0)->pixels!=held_pixels,"Native ambient scroll did not change visible retained canvas");pair.scene();++totals.native_cases;
    }
}

void continuation_domains(const eb::GameAssets& assets) {
    for(unsigned retired:{0u,1u}) {
        Pair pair(assets);pair.context+=" cursor/fallback retired="+std::to_string(retired);pair.fill(1);pair.font(0,1);pair.cursor(5,0);
        if(retired)pair.window(dialogue::WindowAction::Close,1);pair.absent(0);pair.print(0x20,0);require(pair.source.get(pair.source.record(0)+14)==4,"Original initial Saturn decrement differs");
        pair.print(0x41,0);require(pair.source.get(pair.source.record(0)+14)==5 && !pair.source.get(0xa02f),"Original active fallback did not reset/increment");
        // Move to zero using source newlines rather than directly changing a
        // retained cursor. Then exercise two word underflows before recovery.
        pair.newline(0);const unsigned line=pair.source.get(pair.source.record(0)+16);pair.print(0x63,0);
        require(pair.source.get(pair.source.record(0)+14)==0xfffe,"Original diacritic did not preserve two16-bit decrements");pair.print(0x1a,0);
        require(pair.source.get(pair.source.record(0)+14)==0xfffd,"Original sub32 glyph unexpectedly wrapped");pair.print(0x20,0);
        require(pair.source.get(pair.source.record(0)+14)==0 && pair.source.get(pair.source.record(0)+16)==line+1,"Original printable did not recover wrapped cursor");
        pair.scene();++totals.native_cases;
    }
    for(unsigned retired:{0u,1u})for(unsigned code:{0u,15u,65535u}) {
        Pair pair(assets);pair.context+=" fixed no-lookup retired="+std::to_string(retired)+" code="+hex(code);pair.fill(1);
        if(retired)pair.window(dialogue::WindowAction::Close,1);pair.absent(0);pair.policy(false,2);const auto before=pair.source.state(0);pair.print(code,0);
        require(pair.source.state(0).canvas==before.canvas && pair.source.state(0).artwork==before.artwork,"Original unplaced fixed code performed an art lookup");++totals.native_cases;
    }
}
void alias_domains(const eb::GameAssets& assets) {
    Pair pair(assets);pair.context+=" shared publication aliases";pair.fill(1);pair.font(0,1);
    for(unsigned i=0;i<80;++i)pair.print(0x60+(i%12),0);
    pair.window(dialogue::WindowAction::Open,2);const auto second=pair.source.slot(2);require(second==1,"Original second window did not use slot1");pair.fill(2);pair.font(second,1);
    for(unsigned i=0;i<80;++i)pair.print(0x6c+(i%8),second);
    pair.scene();pair.window(dialogue::WindowAction::Close,1);pair.absent(0);pair.policy(true,0);
    const auto immutable=pair.windows.slot_frame(0),immutable_scene=pair.windows.frame();const auto immutable_pixels=immutable->pixels,immutable_scene_pixels=immutable_scene->pixels;
    const auto retained_before=pair.source.canvas(0),live_before=pair.source.canvas(1);const auto scene_before=pair.source.ppu();
    unsigned changed_retained=0,changed_live=0,changed_scene=0;
    for(unsigned i=0;i<72;++i) {
        pair.print(0x60+(i%12),0);pair.compare(pair.source.state(1),1,"other live alias");
        changed_retained+=differences(retained_before,pair.source.canvas(0))>0;changed_live+=differences(live_before,pair.source.canvas(1))>0;
        if(i%9==0){pair.scene(false);changed_scene+=pair.source.ppu()!=scene_before;}
        require(immutable->pixels==immutable_pixels && immutable_scene->pixels==immutable_scene_pixels,"Sampled images changed with shared publication identity");
    }
    require(changed_retained && changed_live && changed_scene,"Source alias corpus did not mutate retained/live/published scene images");
    pair.newline(0);pair.newline(0);pair.newline(0);pair.compare(pair.source.state(1),1,"other live after retained scroll");pair.scene(false);pair.scene();
    std::cout<<"JP shared48-image reuse: retained changes="<<changed_retained<<" live changes="<<changed_live<<" prior scene changes="<<changed_scene<<'\n';++totals.native_cases;
}
void callback_domains(const eb::GameAssets& assets) {
    for(unsigned mode=0;mode<4;++mode) {
        const std::vector<std::uint8_t> script{0x63,0x20,0x6b,1,0x60,2};auto modified=assets;std::copy(script.begin(),script.end(),modified.image.begin()+0x2e8000);
        Pair pair(modified);pair.context+=" DISPLAY lifecycle callback="+std::to_string(mode);pair.fill(1);pair.font(0,1);pair.cursor(0,0);
        if(mode==1 || mode==2)pair.window(dialogue::WindowAction::Close,1);
        if(mode!=0)pair.absent(0);pair.source.put(0x18c24,0);pair.state.unfocused_register_slot=0;pair.policy(false,1);bool entered=false;
        pair.source.at_service=[&](unsigned pc) {
            pair.events.emplace_back(pc,pair.source.state(0));
            if(pc==0xc13502 && !entered) {
                entered=true;
                if(mode==0 || mode==3)pair.source.nested(0xc10141,false,1);
                if(mode!=0)pair.source.nested(0xc106e4,false,mode==1?1:3);
            }
        };
        pair.source.put32(0x1e0e,0xee8000);pair.source.call(0xc18913,true);pair.source.at_service={};require(entered,"Original lifecycle callback absent");const auto final=pair.source.state(0);
        auto program=std::make_shared<dialogue::Program>(eb::GameVersion::JP,std::vector<dialogue::ContentBlock>{{1,0x8000,script}},std::vector<dialogue::Location>{{1,0x8000}});
        dialogue::Conversation conversation(program,pair.windows);conversation.start(dialogue::EntryId{0});unsigned index=0;entered=false;
        const auto compare_event=[&](unsigned pc,const std::string& label){require(index<pair.events.size() && pair.events[index].first==pc,pair.context+" lifecycle effect order differs");pair.compare(pair.events[index].second,0,label+std::to_string(index));++index;};
        for(unsigned n=0;n<100000;++n) {
            const auto status=conversation.advance(7);if(status==dialogue::Progress::Finished)break;if(status==dialogue::Progress::BudgetExhausted)continue;
            const auto* effect=std::get_if<dialogue::TextEffect>(&*conversation.event());require(effect,"Ambient conversation left its text service");const auto pc=effect->kind==dialogue::TextEffectKind::TextSound?0xc0abbfu:0xc13502u;compare_event(pc,"parent effect ");
            if(pc==0xc13502 && !entered) {
                entered=true;const auto held=conversation.event();
                const auto change=[&](dialogue::WindowAction action,unsigned id) {
                    auto child=pair.windows.begin_nested({action,dialogue::WindowId{id}},conversation);
                    while(child->advance()==dialogue::OutputProgress::Suspended) {
                        require(child->effect()->kind==dialogue::WindowEffectKind::ClearPartyBlink,"Unexpected nested window service");compare_event(0xc07eab,"nested world effect ");child->respond();
                    }
                    require(child->complete() && conversation.event()==held,"Window child lost parent pending tick");++totals.nested_lifecycles;
                };
                if(mode==0 || mode==3)change(dialogue::WindowAction::Close,1);
                if(mode!=0)change(dialogue::WindowAction::Open,mode==1?1:3);
            }
            conversation.respond();
        }
        require(conversation.finished() && entered && index==pair.events.size(),pair.context+" whole DISPLAY did not complete");pair.compare(final,0,"DISPLAY final");pair.scene();
        require(conversation.snapshot().returned_cursor==dialogue::Location{1,0x8006},"Native ambient DISPLAY cursor differs");require(pair.source.get(0x1e06)==0x8006 && pair.source.get(0x1e08)==0xee,"Original ambient DISPLAY cursor differs");++totals.native_cases;++totals.complete_streams;totals.native_effects+=index;
    }
}

}
int main(int argc,char** argv){try{
    if(argc<2){std::cout<<"SKIP absent-focus reference: JP local pack required\n";return 77;}
    bool jp=false;for(int i=1;i<argc;++i){const auto assets=eb::load_game_assets(argv[i],eb::asset_profiles());if(assets.version==eb::GameVersion::JP){source_domains(assets);native_domains(assets);continuation_domains(assets);alias_domains(assets);callback_domains(assets);jp=true;}}
    require(jp,"No JP pack supplied");
    std::cout<<"PASS JP absent-focus reference: "<<totals.cases<<" source diagnostic cases, "<<totals.native_cases<<" native differential scenarios, "
        <<totals.complete_streams<<" complete DISPLAY_TEXT streams, "<<totals.nested_lifecycles<<" real nested lifecycle calls, "
        <<totals.native_effects<<" ordered native effects, "<<totals.comparisons<<" semantic/image comparisons, "<<totals.canvas_pixels<<" indexed canvas pixels, "
        <<totals.brush_pixels<<" brush pixels, "<<totals.publication_pixels<<" publication pixels, "<<totals.ppu_pixels<<" actual source PPU pixels, "
        <<totals.steps<<" original instructions, "<<totals.writes<<" diagnostic ordered WRAM writes, "<<totals.dma_acknowledgements<<" completed-DMA acknowledgements\n";
    std::cout<<"Scope: imported JP font/window assets; real source load/create/close/glyph/newline/DISPLAY execution; live and retained physical slots; "
        <<"shared 48-image aliases and immutable samples. WINDOW_TICK, PLAY_SOUND and frame wait are explicit host return seams; "
        <<"nested CREATE/CLOSE retain parent CPU locals/stack. JP completed-DMA semaphore acknowledged at C439E2/C43BE8. "
        <<"No audio/world scheduler or GPU proof.\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
