// Complete original NPC helpers, including real sprite-map generation and DMA.
// Expected state is generated by the original CPU; native execution uses the
// actual imported catalog and Runtime/Scene/ActorWorld/Interactions owners.
#include "native_actor_npc_fixture.hpp"
// The historical oracle main relies on main's implicit return. It is never
// called here; retain that frozen fixture while renaming its entry point.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type"
#define main prior_npc_sprite_reference_main
#include "native_sprite_appearance_reference.cpp"
#undef main
#pragma GCC diagnostic pop
#include "eb/native/dialogue/import.hpp"

namespace {
std::uint64_t npc_instructions{};
unsigned call_npc(Oracle& source,unsigned helper,unsigned incoming=0) {
  source.cpu.program_counter=0xc0ff00;source.cpu.accumulator=std::uint16_t(incoming);
  source.cpu.status_register=eb::MainCpu65816::InterruptDisable;
  source.cpu.execute_instruction<0x22>(helper,4);
  for(unsigned i=0;i<1000000;++i) {
    if(source.cpu.program_counter==0xc0ff04 && source.cpu.stack_pointer==0x1fff)
      return source.cpu.accumulator;
    source.cpu.step_instruction();++npc_instructions;
  }
  throw std::runtime_error("Original NPC helper did not return: "+source.cpu.describe_registers());
}
std::shared_ptr<const ActionScriptData> npc_scripts(eb::GameVersion v) {
  std::vector<std::uint8_t> bytes;std::vector<std::uint32_t> roots;
  const unsigned initial=v==eb::GameVersion::US?0xc46914:0xc44690;
  const unsigned gift=v==eb::GameVersion::US?0xc0c353:0xc0c335;
  const unsigned refresh=v==eb::GameVersion::US?0xc46957:0xc446d3;
  auto call=[&](unsigned address){bytes.insert(bytes.end(),{0x42,std::uint8_t(address),std::uint8_t(address>>8),std::uint8_t(address>>16)});};
  for(unsigned i=0;i<3;++i){roots.push_back(bytes.size());call(i==1?gift:initial);if(i==2)call(refresh);bytes.insert(bytes.end(),{6,1,9});}
  for(unsigned direction=0;direction<8;++direction){roots.push_back(bytes.size());bytes.insert(bytes.end(),{0x1d,std::uint8_t(direction),0});call(refresh);bytes.insert(bytes.end(),{6,1,9});}
  return std::make_shared<ActionScriptData>(std::move(bytes),0,std::move(roots));
}
struct NpcRuntime {
  Fixture base;
  std::shared_ptr<SpriteResources> sprites;
  std::shared_ptr<const NpcCatalog> catalog;
  std::shared_ptr<const ActionScriptData> scripts;
  ActorWorld actors;
  WorldActivation activation;
  WorldEnemies enemies;
  npcs::Interactions interactions;
  std::unique_ptr<WorldRuntime> runtime;
  explicit NpcRuntime(const eb::GameAssets& assets)
      :base(assets.version),sprites(std::make_shared<SpriteResources>(assets.image,sprite_catalog_layout(assets.version))),
       catalog(std::make_shared<NpcCatalog>(assets.image,npc_catalog_layout(assets.version,false))),scripts(npc_scripts(assets.version)),
       actors(sprites,scripts,assets.version),activation(catalog,sprites,scripts,assets.version,{0,8}),
       enemies(make_enemies(),sprites,scripts,{0,0,2}),
       interactions(npcs::InteractionResources::import(assets.image,assets.version),npcs::MapTextResources::import(assets.image,assets.version),
                    dialogue::import_program(assets.image,assets.version).program,base.windows,actors,base.collision,base.area) {
    interactions.bind_event_flags();
    runtime=std::make_unique<WorldRuntime>(base.windows,base.party,base.random,base.meters,base.clock,base.input,actors,activation,enemies,base.collision,
               base.area,base.palettes,base.map,base.colors,base.animations,base.controls,NpcStripAdmission::Admitted);
    runtime->bind_interactions(interactions);
  }
  ActorId add(std::optional<NpcId> npc,unsigned sprite=1) {
    WorldActorSpec spec;spec.npc=npc;spec.sprite=sprite;spec.script=0;
    const auto result=actors.create_authored(spec,{0,1});require(bool(result),"Native reference actor creation failed");return *result;
  }
  unsigned run(ActorId id,unsigned script) {
    actors.replace_script(id,scripts->entry(script));auto op=runtime->begin(story::TickKind::ActorFrame);
    require(next(*op)==dialogue::Progress::Suspended && op->service()==story::SceneService::Frame,"Native NPC call did not reach actual frame boundary");
    const auto value=actors.actor(id).tasks().at(0).temporary;op->complete_frame({});finish(*op);return value;
  }
};
void npc_reference(const eb::GameAssets& assets) {
  NpcRuntime native(assets);Oracle source(assets);const bool us_region=assets.version==eb::GameVersion::US;
  const unsigned npc_table=us_region?0x2c9a:0x3098,flags=us_region?0x9c08:0x9eb3;
  unsigned direction_cases{},gift_cases{},refresh_cases{};std::size_t pixels{};
  for(unsigned index=0;index<=native.catalog->size();++index) {
    const bool sentinel=index==native.catalog->size();const auto id=native.add(sentinel?std::nullopt:std::optional<NpcId>{NpcId(index)});
    source.put(source.l.current_slot,0);source.put(npc_table,sentinel?0xffff:index);
    const auto before=source.get(source.l.direction);
    const auto expected=call_npc(source,us_region?0xc46914:0xc44690,0xa55a);
    require(native.run(id,0)==expected,"Complete initial NPC direction differs");
    require(source.get(source.l.direction)==before,"Original initial direction unexpectedly mutated facing");
    native.actors.erase(id);++direction_cases;
  }
  for(unsigned direction=0;direction<8;++direction) {
    // This helper consumes a script temporary, not an NPC definition. Use
    // actual SET_TEMP words to cover every facing, including catalog-absent ones.
    const auto id=native.add(std::nullopt);auto& actor=native.actors.actor(id);
    source.configure(assets,1);source.put(npc_table,0xffff);
    for(unsigned phase:{0u,2u,0xffffu})for(unsigned surface:{0u,8u,12u})for(bool same:{false,true}) {
      const unsigned old=same?direction:(direction+2)&7;
      actor.behavior.direction=std::uint16_t(old);actor.action().animation=std::uint16_t(phase);actor.behavior.surface_flags=std::uint16_t(surface);
      source.put(source.l.direction,old);source.put(source.l.animation,phase);source.put(source.l.surface,surface);
      const auto picture=actor.appearance.displayed();const auto vram=source.bus->video_ram;
      call_npc(source,us_region?0xc46957:0xc446d3,direction);native.run(id,3+direction);
      require(actor.behavior.direction==source.get(source.l.direction) && actor.action().animation==source.get(source.l.animation),"Conditional facing state differs");
      if(same)require(actor.appearance.displayed()==picture && source.bus->video_ram==vram,"Unchanged facing refreshed graphics");
      else {if(!surface)source.check(assets,actor.appearance);pixels+=source.check_pixels(assets,*native.sprites,actor.appearance);}
      ++refresh_cases;
    }
    native.actors.erase(id);
  }
  for(unsigned npc=0;npc<native.catalog->size();++npc) {
    const auto& definition=native.catalog->definition(NpcId(npc));if(definition.type!=NpcType::ItemBox)continue;
    const auto id=native.add(NpcId(npc),definition.sprite);auto& actor=native.actors.actor(id);source.configure(assets,definition.sprite);source.put(npc_table,npc);
    for(bool open:{false,true})for(unsigned phase:{0u,2u,0xffffu})for(unsigned surface:{0u,8u,12u}) {
      native.base.text.set_flag(definition.event_flag,open);
      std::copy(native.base.text.event_flags.begin(),native.base.text.event_flags.end(),source.bus->work_ram.begin()+flags);
      actor.behavior.direction=6;actor.action().animation=std::uint16_t(phase);actor.behavior.surface_flags=std::uint16_t(surface);
      source.put(source.l.direction,6);source.put(source.l.animation,phase);source.put(source.l.surface,surface);
      const auto saved_flags=native.base.text.event_flags;
      call_npc(source,us_region?0xc0c353:0xc0c335,0xbeef);native.run(id,1);
      require(actor.behavior.direction==source.get(source.l.direction) && actor.action().animation==source.get(source.l.animation),"Complete gift refresh state differs");
      require(native.base.text.event_flags==saved_flags && std::equal(saved_flags.begin(),saved_flags.end(),source.bus->work_ram.begin()+flags),"Gift refresh mutated event flags");
      if(!surface)source.check(assets,actor.appearance);
      pixels+=source.check_pixels(assets,*native.sprites,actor.appearance);++gift_cases;
    }
    native.actors.erase(id);
  }
  require(direction_cases>1500 && refresh_cases==144 && gift_cases>0 && pixels>0,"NPC source proof lacked required coverage");
  std::cout<<(us_region?"US":"JP")<<" NPC helpers: "<<direction_cases<<" directions, "<<refresh_cases<<" conditional refreshes, "<<gift_cases<<" gift refreshes, "<<pixels<<" sprite pixels, "<<npc_instructions<<" original instructions\n";
}
}
int main(int argc,char**argv) {
  try {if(argc<2)return 77;for(int i=1;i<argc;++i)npc_reference(eb::load_game_assets(argv[i],eb::asset_profiles()));return 0;}
  catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}
}
